# **Predicting Earth-Like Similarity in Exoplanets: Modeling Experiments**

## **Preparing the Dataset for Modeling**

In [442]:
# general importing
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# K-Nearest Neighbor importing
from sklearn.impute import KNNImputer
from sklearn.neighbors import NearestNeighbors
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.decomposition import PCA
from sklearn.pipeline import Pipeline

# regex importing for pattern recognition
import re

In [443]:
# loading dataset
new_exoplanets_filtered4 = pd.read_csv('/content/drive/MyDrive/Exoplanet /filtered_2026_dataset_new_final3.csv')

In [444]:
new_exoplanets_filtered4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5419 entries, 0 to 5418
Data columns (total 15 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   planet_name                   5419 non-null   object 
 1   star_number_per_system        5419 non-null   float64
 2   spectral_type                 5419 non-null   object 
 3   orbital_period_day            5419 non-null   float64
 4   orbit_semi_major_axis_au      5419 non-null   float64
 5   planet_rad_earth_rad          5419 non-null   float64
 6   planet_mass_earth_mass        5419 non-null   float64
 7   planet_equil_temp_k           5419 non-null   float64
 8   stellar_effective_temp_k      5419 non-null   float64
 9   stellar_rad_solar_rad         5419 non-null   float64
 10  stellar_mass_solar_mass       5419 non-null   float64
 11  stellar_surf_grav             5419 non-null   float64
 12  stellar_luminosity_solar_lum  5419 non-null   float64
 13  pla

In [445]:
# viewing all rows which are within the habitable zone of its star
new_exoplanets_filtered4[new_exoplanets_filtered4['habitable_zone_main_seq'] == 1]

,planet_name,star_number_per_system,spectral_type,orbital_period_day,orbit_semi_major_axis_au,planet_rad_earth_rad,planet_mass_earth_mass,planet_equil_temp_k,stellar_effective_temp_k,stellar_rad_solar_rad,stellar_mass_solar_mass,stellar_surf_grav,stellar_luminosity_solar_lum,planet_orbital_velocity,habitable_zone_main_seq
28,55 Cnc f,2.0,GV,260.78125,0.781513,6.344191,47.529849,235.917959,5241.127143,0.963067,0.924286,4.412356,0.627916,1.087703,1
45,AU Mic e,1.0,KV,33.25000,0.170681,4.301580,21.100000,325.735064,3665.000000,0.820000,0.600000,4.520000,0.108846,1.875246,1
59,BD+49 828 b,1.0,KV,2590.00000,4.200000,19.718599,508.500000,269.617897,4943.000000,7.600000,1.520000,2.850000,30.937091,0.601689,1
64,BD-11 4672 c,1.0,KV,74.20000,0.300000,3.696464,15.370000,269.263294,4550.000000,0.639000,0.651000,4.642000,0.157014,1.473346,1
143,EPIC 212737443 c,1.0,KV,65.55000,0.280000,2.690000,6.554346,316.000000,4684.000000,0.673000,0.690000,4.622000,0.195608,1.570075,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4961,TOI-4633 c,2.0,GV,271.94450,0.847000,3.200000,123.000000,261.852602,5800.000000,1.050000,1.100000,4.436836,1.119387,1.139803,1
4978,TOI-500 e,1.0,KV,61.30000,0.275206,3.659440,15.050000,282.582374,4440.000000,0.678000,0.740000,4.618000,0.160281,1.640069,1
5016,TOI-544 c,1.0,KV,50.08900,0.228093,4.340406,21.500000,279.380615,4169.000000,0.623000,0.631000,4.680000,0.105195,1.663543,1
5097,TOI-712 d,1.0,KV,84.83960,0.340500,2.474000,5.590613,313.600000,4622.000000,0.674000,0.732000,4.645000,0.186007,1.466466,1


In [446]:
# viewing row for kepler-452 b
new_exoplanets_filtered4[new_exoplanets_filtered4['planet_name'] == 'Kepler-452 b']

,planet_name,star_number_per_system,spectral_type,orbital_period_day,orbit_semi_major_axis_au,planet_rad_earth_rad,planet_mass_earth_mass,planet_equil_temp_k,stellar_effective_temp_k,stellar_rad_solar_rad,stellar_mass_solar_mass,stellar_surf_grav,stellar_luminosity_solar_lum,planet_orbital_velocity,habitable_zone_main_seq
3674,Kepler-452 b,1.0,GV,384.844831,1.009733,1.63,3.294107,235.0,5687.166667,1.099285,1.029667,4.44555,1.134212,1.009997,1


In [447]:
# viewing row for Kepler-22 b
new_exoplanets_filtered4[new_exoplanets_filtered4['planet_name'] == 'Kepler-22 b']

,planet_name,star_number_per_system,spectral_type,orbital_period_day,orbit_semi_major_axis_au,planet_rad_earth_rad,planet_mass_earth_mass,planet_equil_temp_k,stellar_effective_temp_k,stellar_rad_solar_rad,stellar_mass_solar_mass,stellar_surf_grav,stellar_luminosity_solar_lum,planet_orbital_velocity,habitable_zone_main_seq
3069,Kepler-22 b,1.0,GV,289.863821,0.829829,2.191111,9.1,264.142857,5589.090909,0.881097,0.951875,4.478131,0.679676,1.0712,1


In [448]:
# viewing row for Kepler-1638 b
new_exoplanets_filtered4[new_exoplanets_filtered4['planet_name'] == 'Kepler-1638 b']

,planet_name,star_number_per_system,spectral_type,orbital_period_day,orbit_semi_major_axis_au,planet_rad_earth_rad,planet_mass_earth_mass,planet_equil_temp_k,stellar_effective_temp_k,stellar_rad_solar_rad,stellar_mass_solar_mass,stellar_surf_grav,stellar_luminosity_solar_lum,planet_orbital_velocity,habitable_zone_main_seq
2534,Kepler-1638 b,1.0,GV,259.338308,0.78415,1.87,4.605677,328.75,5737.888889,0.95,0.917571,4.206098,0.877699,1.081921,1


-----------

# **Proposed Method K Nearest Neighbor (KNN) Models**
Used to idenfity the top 10 most Earth-Like Exoplanets by comparing all exoplanets (represented as datapoints) to a synthetically created "target row" Earth. The features of all exoplanets are then compared to the features of Earth based on the Manhattan Distance and the Euclidean Distance between data points. The closer the match (most Earth-Like) the smaller the distance from Earth.

Two KNN Models will be created. The first KNN Model will be using the Manhattan Distance. The second KNN Model will be using the Euclidean Distance. Both models will use the Minkowski DIstance which will be fine tuned based on if the value p=1 or p=2 which corresponds to the Manhatten Distance or Euclidean Distance respectively.


#### Preparing Dataset

In [449]:
# creating copy of dataset for KNN Model
new_exoplanets_filtered_KNN = new_exoplanets_filtered4.copy()

#### Ensure all features are normalized in terms of Earth

In [450]:
# Normalize the orbital period column
new_exoplanets_filtered_KNN['orbital_period_day'] = new_exoplanets_filtered_KNN['orbital_period_day'] / 365.26

# Normalize the planet equilibrium temperature
new_exoplanets_filtered_KNN['planet_equil_temp_k'] = new_exoplanets_filtered_KNN['planet_equil_temp_k'] / 255.0

# Normalize the stellar effective temperature
new_exoplanets_filtered_KNN['stellar_effective_temp_k'] = new_exoplanets_filtered_KNN['stellar_effective_temp_k'] / 5772.0

#### Creating Target Row for Earth

In [451]:
# creating a target row called Earth which all the other rows will be compared to (similarity search)
earth = pd.DataFrame({'planet_name': ['Earth'],
                      'star_number_per_system': [1.0],
                      'orbital_period_day': [1.0],
                      'orbit_semi_major_axis_au':[1.0],
                      'planet_rad_earth_rad': [1.0],
                      'planet_mass_earth_mass': [1.0],
                      'planet_equil_temp_k': [1.0],
                      'spectral_type': ['GV'],
                      'stellar_effective_temp_k': [1.0],
                      'stellar_rad_solar_rad': [1.0],
                      'stellar_mass_solar_mass': [1.0],
                      'stellar_surf_grav': [1.0],
                      'stellar_luminosity_solar_lum': [1.0],
                      'planet_orbital_velocity': [1.0],
                      'habitable_zone_main_seq': [1]})

In [452]:
earth

,planet_name,star_number_per_system,orbital_period_day,orbit_semi_major_axis_au,planet_rad_earth_rad,planet_mass_earth_mass,planet_equil_temp_k,spectral_type,stellar_effective_temp_k,stellar_rad_solar_rad,stellar_mass_solar_mass,stellar_surf_grav,stellar_luminosity_solar_lum,planet_orbital_velocity,habitable_zone_main_seq
0,Earth,1.0,1.0,1.0,1.0,1.0,1.0,GV,1.0,1.0,1.0,1.0,1.0,1.0,1


In [453]:
earth.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 15 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   planet_name                   1 non-null      object 
 1   star_number_per_system        1 non-null      float64
 2   orbital_period_day            1 non-null      float64
 3   orbit_semi_major_axis_au      1 non-null      float64
 4   planet_rad_earth_rad          1 non-null      float64
 5   planet_mass_earth_mass        1 non-null      float64
 6   planet_equil_temp_k           1 non-null      float64
 7   spectral_type                 1 non-null      object 
 8   stellar_effective_temp_k      1 non-null      float64
 9   stellar_rad_solar_rad         1 non-null      float64
 10  stellar_mass_solar_mass       1 non-null      float64
 11  stellar_surf_grav             1 non-null      float64
 12  stellar_luminosity_solar_lum  1 non-null      float64
 13  planet_or

#### Setting planet name as the index (since planet name is the observation)

In [454]:
# set planet name as index for earth row
earth.set_index('planet_name', inplace=True)

# setting the planet_name as the index
new_exoplanets_filtered_KNN.set_index('planet_name', inplace=True)

In [455]:
new_exoplanets_filtered_KNN.head()

,star_number_per_system,spectral_type,orbital_period_day,orbit_semi_major_axis_au,planet_rad_earth_rad,planet_mass_earth_mass,planet_equil_temp_k,stellar_effective_temp_k,stellar_rad_solar_rad,stellar_mass_solar_mass,stellar_surf_grav,stellar_luminosity_solar_lum,planet_orbital_velocity,habitable_zone_main_seq
planet_name,,,,,,,,,,,,,,
11 Com b,2.0,GIII,0.888737,1.226000,61.636581,5505.066162,2.561322,0.832987,13.760000,2.090000,2.380000,90.778824,1.305879,0
11 UMi b,1.0,KIII,1.413295,1.526667,57.057421,4684.814200,2.856345,0.740904,26.935000,2.780000,1.765000,217.709668,1.349663,0
14 And b,1.0,KIII,0.510048,0.761667,30.026230,1224.550434,2.967550,0.840350,11.275000,1.780000,2.590000,63.134826,1.528982,0
14 Her b,1.0,KV,4.835948,2.814750,42.726171,2559.472162,0.501817,0.917704,0.999085,0.904000,4.418006,0.705033,0.566812,0
16 Cyg B b,3.0,GV,2.188510,1.662833,20.176910,533.514528,0.750641,0.992480,1.129135,1.016599,4.342293,1.231895,0.782034,0


In [456]:
earth.head()

,star_number_per_system,orbital_period_day,orbit_semi_major_axis_au,planet_rad_earth_rad,planet_mass_earth_mass,planet_equil_temp_k,spectral_type,stellar_effective_temp_k,stellar_rad_solar_rad,stellar_mass_solar_mass,stellar_surf_grav,stellar_luminosity_solar_lum,planet_orbital_velocity,habitable_zone_main_seq
planet_name,,,,,,,,,,,,,,
Earth,1.0,1.0,1.0,1.0,1.0,1.0,GV,1.0,1.0,1.0,1.0,1.0,1.0,1


In [457]:
new_exoplanets_filtered_KNN.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5419 entries, 11 Com b to xi Aql b
Data columns (total 14 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   star_number_per_system        5419 non-null   float64
 1   spectral_type                 5419 non-null   object 
 2   orbital_period_day            5419 non-null   float64
 3   orbit_semi_major_axis_au      5419 non-null   float64
 4   planet_rad_earth_rad          5419 non-null   float64
 5   planet_mass_earth_mass        5419 non-null   float64
 6   planet_equil_temp_k           5419 non-null   float64
 7   stellar_effective_temp_k      5419 non-null   float64
 8   stellar_rad_solar_rad         5419 non-null   float64
 9   stellar_mass_solar_mass       5419 non-null   float64
 10  stellar_surf_grav             5419 non-null   float64
 11  stellar_luminosity_solar_lum  5419 non-null   float64
 12  planet_orbital_velocity       5419 non-null   float64
 1

In [458]:
earth.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1 entries, Earth to Earth
Data columns (total 14 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   star_number_per_system        1 non-null      float64
 1   orbital_period_day            1 non-null      float64
 2   orbit_semi_major_axis_au      1 non-null      float64
 3   planet_rad_earth_rad          1 non-null      float64
 4   planet_mass_earth_mass        1 non-null      float64
 5   planet_equil_temp_k           1 non-null      float64
 6   spectral_type                 1 non-null      object 
 7   stellar_effective_temp_k      1 non-null      float64
 8   stellar_rad_solar_rad         1 non-null      float64
 9   stellar_mass_solar_mass       1 non-null      float64
 10  stellar_surf_grav             1 non-null      float64
 11  stellar_luminosity_solar_lum  1 non-null      float64
 12  planet_orbital_velocity       1 non-null      float64
 13  habita

#### Encoding Categorical Columns
OneHotEncoder is used because it creates 21 new binary columns corresponding to the unique spectral type entries:
* GIII, KIII, KV, GV, GIV, KIV, MV, sdB, FIV, FV, KII, SD, AV, MIII, AIII, BV, AIV, WD, T, BIV, GII

So, for example:
* If spectral_type_GV == 1 --> may increase habitability probability
* If spectral_type_MV == 1 --> may increase habitability probability
* If spectral_type_WD == 1 --> may decrease habitability probability

In [459]:
new_exoplanets_filtered_KNN['spectral_type'].unique()

array(['GIII', 'KIII', 'KV', 'GV', 'GIV', 'KIV', 'MV', 'sdB', 'FIV', 'FV',
       'KII', 'SD', 'AV', 'MIII', 'AIII', 'BV', 'AIV', 'WD', 'T', 'BIV',
       'GII'], dtype=object)

In [460]:
# Combine both for fitting the OneHotEncoder to prevent unseen label errors
combined_spectral_type = pd.concat([new_exoplanets_filtered_KNN['spectral_type'], earth['spectral_type']], ignore_index=True)

# Ensure combined_spectral_type is a DataFrame with 1 column
combined_spectral_type_df = pd.DataFrame(combined_spectral_type, columns=['spectral_type'])

# Fit the OneHotEncoder for categorical columns
encoder = OneHotEncoder(sparse_output=False, handle_unknown='ignore')
encoder.fit(combined_spectral_type_df)

# Transform both the original cleaned dataset and the earth target row dataset
new_exoplanets_filtered_KNN_encoded = encoder.transform(new_exoplanets_filtered_KNN[['spectral_type']])
earth_encoded = encoder.transform(earth[['spectral_type']])

# Generate column names for the encoded columns
encoded_columns = encoder.get_feature_names_out(['spectral_type'])

# Convert to DataFrame and ensure indices match
new_exoplanets_filtered_KNN_encoded = pd.DataFrame(
    new_exoplanets_filtered_KNN_encoded,
    columns=encoded_columns,
    index=new_exoplanets_filtered_KNN.index
)
earth_encoded = pd.DataFrame(
    earth_encoded,
    columns=encoded_columns,
    index=earth.index
)

# Drop orignal spectral_type column since we have generated encoded columns
new_exoplanets_filtered_KNN = new_exoplanets_filtered_KNN.drop(columns=['spectral_type'])
earth = earth.drop(columns=['spectral_type'])

# Add encoded columns back into original cleaned dataset and earth
new_exoplanets_filtered_KNN = pd.concat([new_exoplanets_filtered_KNN, new_exoplanets_filtered_KNN_encoded], axis=1)
earth = pd.concat([earth, earth_encoded], axis=1)

In [461]:
new_exoplanets_filtered_KNN.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5419 entries, 11 Com b to xi Aql b
Data columns (total 34 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   star_number_per_system        5419 non-null   float64
 1   orbital_period_day            5419 non-null   float64
 2   orbit_semi_major_axis_au      5419 non-null   float64
 3   planet_rad_earth_rad          5419 non-null   float64
 4   planet_mass_earth_mass        5419 non-null   float64
 5   planet_equil_temp_k           5419 non-null   float64
 6   stellar_effective_temp_k      5419 non-null   float64
 7   stellar_rad_solar_rad         5419 non-null   float64
 8   stellar_mass_solar_mass       5419 non-null   float64
 9   stellar_surf_grav             5419 non-null   float64
 10  stellar_luminosity_solar_lum  5419 non-null   float64
 11  planet_orbital_velocity       5419 non-null   float64
 12  habitable_zone_main_seq       5419 non-null   int64  
 1

In [462]:
earth.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1 entries, Earth to Earth
Data columns (total 34 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   star_number_per_system        1 non-null      float64
 1   orbital_period_day            1 non-null      float64
 2   orbit_semi_major_axis_au      1 non-null      float64
 3   planet_rad_earth_rad          1 non-null      float64
 4   planet_mass_earth_mass        1 non-null      float64
 5   planet_equil_temp_k           1 non-null      float64
 6   stellar_effective_temp_k      1 non-null      float64
 7   stellar_rad_solar_rad         1 non-null      float64
 8   stellar_mass_solar_mass       1 non-null      float64
 9   stellar_surf_grav             1 non-null      float64
 10  stellar_luminosity_solar_lum  1 non-null      float64
 11  planet_orbital_velocity       1 non-null      float64
 12  habitable_zone_main_seq       1 non-null      int64  
 13  spectr

#### Defining Weights for Key Features
Justification of Feature Weights for Earth-Analog Identification:

* **Highest Weights (7.0): Habitability-Critical Parameters:**
  * orbital_period_day = 7.0
  * habitable_zone_main_seq = 7.0
  * spectral_type_GV = 7.0
* These receive the strongest weighting because long-term habitability depends primarily on:
  * Stable orbital configuration
  * Location within the circumstellar habitable zone
  * Host star similarity to the Sun
* The concept of the circumstellar habitable zone originates from previous work on astrophyical analyis of habitable zones of main sequence stars demonstrates that surface liquid water stability is primarily governed by stellar flux and orbital distance.
* Solar-type stars such as Sun which have a spectral type GV (Star Type G Main Sequence V stars) provide:
  * Stable luminosity
  * Moderate UV radiation
  * Long main-sequence lifetimes
* The strong weight on spectral_type_GV reflects the hypothesis that true Earth analogs must orbit Sun-like main-sequence stars.
* The strong weight on habitable_zone_main_seq encodes this astrophysical constraint directly into the similarity metric.

* **High Weights (6.0): Radiative & Orbital Energy Balance:**
  * planet_equil_temp_k = 6.0
  * orbit_semi_major_axis_au = 6.0
* Equilibrium temperature describes planetary surface conditions and radiative balance
* Small deviations in orbital distance significantly alter stellar flux.
* The amount of stellar radiation (energy per unit area) a planet receives from its host star determines whether a planet is frozen, temperate, or in a runaway greenhouse state. Therefore, these parameters are weighted heavily.
* This aligns with classical habitable zone modeling and energy balance studies.

* **Moderate Weight (5.0): Planetary Radius:**
  * planet_rad_earth_rad = 5.0
* Radius is strongly correlated with bulk composition.
* Observational and theoretical work shows:
  * Planets which have a radii above about 1.5 Earth radii are likely Super-Earth Like while exoplanets beyond approximately 2 Earth radii are likely volatile-rich Neptune Like planets.
* Rocky composition probability declines sharply beyond that threshold.
* Thus radius is given substantial weight because Composition (rocky vs gaseous) is critical for Earth analog status.

* **Lower Weight (1.5): Stellar Mass and Radius Parameters:**
  * stellar_mass_solar_mass = 1.5
  * stellar_rad_solar_rad = 1.5
* Since the GV spectral type can range from G0v to G8v where the large the number indicates larger, brighter, and more massive Type G main sequence stars, applying a slight weight to the stellar mass and stellar radius ensure the planet's host star exhibit similar physical characteristics to the Sun which is G2V.
* Heavy weighting was not applied to avoid over-weighting since the equilibrium (average surface) planet temperature and habitable zone modeling already provides insight into these physical characteristics.

* **No Weight (1.0): Planetary Mass**
  * planet_mass_earth_mass = 1.0
* This may be surprising since Mass similarity is an important factor to consider.
* Mass is often more uncertain observationally since at larger distances, the ability to accurately observe, measure, and calculate the planet's mass becomes a challenge.
* So, many exoplanets lack precise mass measurements, so over-weighting mass could bias the ranking toward well-characterized systems rather than physically similar ones.
* However since Mass and radius are correlated. Radius alone already carries strong compositional information,

* **No Weight (1.0): Stellar Physical Parameters:**
  * stellar_surf_grav = 1.0
  * stellar_luminosity_solar_lum = 1.0
  * stellar_effective_temp_k = 1.0
* These are given baseline weights because their influence is already indirectly captured through equilibrum (average surface) planet temperature and habitable zone modeling.
* Over-weighting them would double-count stellar effects.

* **No Weight (1.0): All Other Non-GV Spectral Types:**
  * All non-GV spectral types = 1.0
* Avoid artificially penalizing potentially habitable Type K or Type M Main Sequence systems
* But still encode strong preference for solar analog systems via GV = 7.0
* This reflects a conservative astrophysical bias rather than excluding non-solar hosts outright.

In [463]:
# Define weights (same order as columns)
weights = {
    'star_number_per_system': 1.0,
    'orbital_period_day': 7.0,
    'orbit_semi_major_axis_au': 6.0,
    'planet_rad_earth_rad': 5.0,
    'planet_mass_earth_mass': 1.0,
    'planet_equil_temp_k': 6.0,
    'stellar_effective_temp_k': 1.0,
    'stellar_rad_solar_rad': 1.5,
    'stellar_mass_solar_mass': 1.5,
    'stellar_surf_grav': 1.0,
    'stellar_luminosity_solar_lum': 1.0,
    'planet_orbital_velocity': 1.0,
    'spectral_type_AIII': 1.0,
    'spectral_type_AIV': 1.0,
    'spectral_type_AV': 1.0,
    'spectral_type_BIV': 1.0,
    'spectral_type_BV': 1.0,
    'spectral_type_FIV': 1.0,
    'spectral_type_FV': 1.0,
    'spectral_type_GII': 1.0,
    'spectral_type_GIII': 1.0,
    'spectral_type_GIV': 1.0,
    'spectral_type_GV': 7.0,
    'spectral_type_KII': 1.0,
    'spectral_type_KIII': 1.0,
    'spectral_type_KIV': 1.0,
    'spectral_type_KV': 1.0,
    'spectral_type_MIII': 1.0,
    'spectral_type_MV': 1.0,
    'spectral_type_SD': 1.0,
    'spectral_type_T': 1.0,
    'spectral_type_WD': 1.0,
    'spectral_type_sdB': 1.0,
    'habitable_zone_main_seq': 7.0,
}

# Apply weights
new_exoplanets_filtered_KNN_weighted = new_exoplanets_filtered_KNN.copy()
earth_weighted = earth.copy()

for col in new_exoplanets_filtered_KNN_weighted.columns:
    weight = weights.get(col, 1.0)
    new_exoplanets_filtered_KNN_weighted[col] *= weight
    earth_weighted[col] *= weight

# This will turn the manhattan distance into a weighted manhattan distance and the euclidean distance into the weighted euclidean distance

### **Current KNN Model using Manhattan Distance (Proposed Method KNN Model #1)**

In [464]:
# Fit Nearest Neighbors model with 10 closest neighbors using minkowski distance where p = 1 (manhattan distance)
nbrs = NearestNeighbors(n_neighbors=10, metric='minkowski', p=1).fit(new_exoplanets_filtered_KNN_weighted)

# Find the top 10 most similar rows
distances, indices = nbrs.kneighbors(earth_weighted)

# Retrieve the 10 closest planet names
closest_planets_man = new_exoplanets_filtered_KNN.index[indices[0]].tolist()
closest_distances_man = distances[0].tolist()

# Print the results
print("Top 10 most similar planets:")
for i in range(10):
    print(f"{i+1}. {closest_planets_man[i]} (Distance: {closest_distances_man[i]:.4f})")

Top 10 most similar planets:
1. Kepler-452 b (Distance: 10.1463)
2. Kepler-1638 b (Distance: 16.6309)
3. Kepler-51 e (Distance: 16.7816)
4. Kepler-1606 b (Distance: 19.2840)
5. Kepler-1701 b (Distance: 20.1409)
6. Kepler-22 b (Distance: 20.8885)
7. Kepler-1126 c (Distance: 22.4542)
8. Kepler-1549 b (Distance: 22.9228)
9. Kepler-1690 b (Distance: 23.2328)
10. Kepler-69 c (Distance: 23.5054)


The closest match to Earth in weighted feature space and thus, could exhibit a potential for habitabiltiy given its similarity to Earth and the Sun, is Kepler-452 b where its Manhattan distance was about 10.146 units away from Earth. The difference in the Manhattan distance of Kepler-452 b is substantal compared to all other top 10 exoplanets as the difference between Kepler-452 b and the second and third closest matches is approcimately 6.6 units.

Kepler-1638 b was the second closest match followed by kepler 51 e which is the third closest match with a difference in manhattan distances of about 16.631 and 16.782 respectively.

In [465]:
all_distances, all_indices = nbrs.kneighbors(earth_weighted, n_neighbors=len(new_exoplanets_filtered_KNN_weighted))

# Map indices to names
all_planets = new_exoplanets_filtered_KNN_weighted.index[all_indices[0]]

# enter name of specifc planet to check its ranking
planet_to_check = 'Kepler-430 c'

# Find rank of Kepler-452 b
if planet_to_check in all_planets:
    rank = list(all_planets).index(planet_to_check) + 1
    distance = all_distances[0][rank-1]
    print(f"{planet_to_check} is ranked #{rank} overall with distance {distance:.4f}")
else:
    print(f"{planet_to_check} not found in dataset.")

Kepler-430 c is ranked #35 overall with distance 29.8656


In [466]:
# df_weighted is already a DataFrame
df_imputed = new_exoplanets_filtered_KNN_weighted.copy()

# Extract Earth's feature vector correctly
earth_vector = earth_weighted.iloc[0]

# Pick the closest planet (rank 1)
closest_planet_man_name = closest_planets_man[0]
planet_vector = df_imputed.loc[closest_planet_man_name]

# Compute Manhattan feature contributions
feature_contributions = (planet_vector - earth_vector).abs()

# Sort by importance
feature_contributions = feature_contributions.sort_values(ascending=False)

print(F"The most Earth-Like planet is: {closest_planet_man_name}")
print("Feature contributions to Manhattan distance:")
print(feature_contributions)

The most Earth-Like planet is: Kepler-452 b
Feature contributions to Manhattan distance:
stellar_surf_grav               3.445550
planet_rad_earth_rad            3.150000
planet_mass_earth_mass          2.294107
planet_equil_temp_k             0.470588
orbital_period_day              0.375332
stellar_rad_solar_rad           0.148928
stellar_luminosity_solar_lum    0.134212
orbit_semi_major_axis_au        0.058400
stellar_mass_solar_mass         0.044500
stellar_effective_temp_k        0.014697
planet_orbital_velocity         0.009997
star_number_per_system          0.000000
habitable_zone_main_seq         0.000000
spectral_type_AIII              0.000000
spectral_type_AIV               0.000000
spectral_type_AV                0.000000
spectral_type_BIV               0.000000
spectral_type_BV                0.000000
spectral_type_FIV               0.000000
spectral_type_FV                0.000000
spectral_type_GII               0.000000
spectral_type_GIII              0.000000
spectral_

When looking to see which feature differed the most for the most Earth-Like planet, the stellar surface gravity presented the greatest deviation though the difference is somewhat minimal. This is followed by the planet's radius and mass. This aligns with current observation since Kepler-452 b in Super-Earth Like in both mass and radius while its stellar surface gravity is slightly greater than that of the Sun's.

In [467]:
# saving the rows associated with the top 10 earth like planets into a dataframe
closest_planets_man_list = new_exoplanets_filtered_KNN_weighted.loc[closest_planets_man]
closest_planets_man_list

,star_number_per_system,orbital_period_day,orbit_semi_major_axis_au,planet_rad_earth_rad,planet_mass_earth_mass,planet_equil_temp_k,stellar_effective_temp_k,stellar_rad_solar_rad,stellar_mass_solar_mass,stellar_surf_grav,...,spectral_type_KII,spectral_type_KIII,spectral_type_KIV,spectral_type_KV,spectral_type_MIII,spectral_type_MV,spectral_type_SD,spectral_type_T,spectral_type_WD,spectral_type_sdB
planet_name,,,,,,,,,,,,,,,,,,,,,
Kepler-452 b,1.0,7.375332,6.058400,8.150000,3.294107,5.529412,0.985303,1.648928,1.544500,4.445550,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Kepler-1638 b,1.0,4.970071,4.704900,9.350000,4.605677,7.735294,0.994090,1.425000,1.376357,4.206098,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Kepler-51 e,1.0,4.993714,4.725706,10.377172,4.600000,5.689555,0.983021,1.305000,1.440000,4.541055,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Kepler-1606 b,1.0,3.764591,3.839040,10.420000,4.035577,6.795294,0.946188,1.239334,1.372500,4.543631,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Kepler-1701 b,1.0,3.241357,3.409560,10.341552,3.978046,6.511765,0.909607,1.191304,1.300500,4.556486,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Kepler-22 b,1.0,5.555075,4.978971,10.955556,9.100000,6.215126,0.968311,1.321646,1.427812,4.478131,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Kepler-1126 c,1.0,3.826492,3.840864,7.842500,2.999040,7.194118,1.010036,1.381459,1.349625,4.500237,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Kepler-1549 b,1.0,4.118144,4.135500,13.073333,6.209992,6.376471,0.915127,1.327141,1.305600,4.487316,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Kepler-1690 b,1.0,4.496655,4.288320,13.500910,6.601563,6.494118,0.964917,1.278222,1.348200,4.517811,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0


### **Current K Nearest Neighbor Model using Euclidean Distance (Proposed Method KNN Model #2)**

In [468]:
# Fit Nearest Neighbors model with 10 closest neighbors using minkowski distance where p = 2 (euclidean distance)
nbrs = NearestNeighbors(n_neighbors=10, metric='minkowski', p=2).fit(new_exoplanets_filtered_KNN_weighted)

# Find the top 10 most similar rows
distances, indices = nbrs.kneighbors(earth_weighted)

# Retrieve the 10 closest planet names
closest_planets_euc = new_exoplanets_filtered_KNN.index[indices[0]].tolist()
closest_distances_euc = distances[0].tolist()

# Print the results
print("Top 10 most similar planets:")
for i in range(10):
    print(f"{i+1}. {closest_planets_euc[i]} (Distance: {closest_distances_euc[i]:.4f})")

Top 10 most similar planets:
1. Kepler-452 b (Distance: 5.2408)
2. Kepler-1638 b (Distance: 7.1452)
3. Kepler-51 e (Distance: 7.7652)
4. Kepler-1606 b (Distance: 8.2007)
5. Kepler-1701 b (Distance: 8.4660)
6. Kepler-1126 c (Distance: 9.4643)
7. Kepler-69 c (Distance: 9.9627)
8. Kepler-1185 b (Distance: 10.3500)
9. Kepler-442 b (Distance: 10.3699)
10. Kepler-311 d (Distance: 10.3847)


The closest match to Earth in weighted feature space and thus, could exhibit a potential for habitabiltiy given its similarity to Earth the Sun, is Kepler-452 b where its euclidean distance was about 5.241 units away from Earth. The difference in the euclidean distance of Kepler-452 b is relatively substantal compared to all other top 10 exoplanets as the difference between Kepler-452 b and the second closest match is about 2 units.

Kepler-1638 b, kepler 51 e, kepler-1606 b, and kepler-1701 b remained in their postions while kepler-22 b dropped from 6th place to 13th place. This is because The ranking of Earth-analog candidates varied depending on the distance metric. Manhattan distance prioritized planets with overall distributed similarity across features, whereas Euclidean distance penalized planets with large deviations in any single feature. Since Kepler-22 b had a larger mass of 9.1 times that of Earth's regardless of the overall similairty of all other features, the Euclidean distance penalized the larger deviation in mass.

In [469]:
all_distances, all_indices = nbrs.kneighbors(earth_weighted, n_neighbors=len(new_exoplanets_filtered_KNN_weighted))

# Map indices to names
all_planets = new_exoplanets_filtered_KNN_weighted.index[all_indices[0]]

# enter name of specifc planet to check its ranking
planet_to_check = 'Kepler-22 b'

# Find rank of Kepler-452 b
if planet_to_check in all_planets:
    rank = list(all_planets).index(planet_to_check) + 1
    distance = all_distances[0][rank-1]
    print(f"{planet_to_check} is ranked #{rank} overall with distance {distance:.4f}")
else:
    print(f"{planet_to_check} not found in dataset.")

Kepler-22 b is ranked #13 overall with distance 10.7934


In [470]:
# df_weighted is already a DataFrame
df_imputed = new_exoplanets_filtered_KNN_weighted.copy()

# Extract Earth's feature vector correctly
earth_vector = earth_weighted.iloc[0]

# Pick the closest planet (rank 1)
closest_planet_euc_name = closest_planets_euc[0]
planet_vector = df_imputed.loc[closest_planet_euc_name]

# Compute squared differences (Euclidean contributions before sqrt)
feature_contributions = (planet_vector - earth_vector) ** 2

# Sort by importance
feature_contributions = feature_contributions.sort_values(ascending=False)

print(F"The most Earth-Like planet is: {closest_planet_euc_name}")
print("Feature contributions to Euclidean distance (squared terms):")
print(feature_contributions)

The most Earth-Like planet is: Kepler-452 b
Feature contributions to Euclidean distance (squared terms):
stellar_surf_grav               11.871815
planet_rad_earth_rad             9.922500
planet_mass_earth_mass           5.262929
planet_equil_temp_k              0.221453
orbital_period_day               0.140874
stellar_rad_solar_rad            0.022179
stellar_luminosity_solar_lum     0.018013
orbit_semi_major_axis_au         0.003411
stellar_mass_solar_mass          0.001980
stellar_effective_temp_k         0.000216
planet_orbital_velocity          0.000100
star_number_per_system           0.000000
habitable_zone_main_seq          0.000000
spectral_type_AIII               0.000000
spectral_type_AIV                0.000000
spectral_type_AV                 0.000000
spectral_type_BIV                0.000000
spectral_type_BV                 0.000000
spectral_type_FIV                0.000000
spectral_type_FV                 0.000000
spectral_type_GII                0.000000
spectral_type

When looking to see which feature differed the most for the most Earth-Like planet, there is a similar trend to that of the manhattan distance KNN model. However, this time the difference appears to be substantially larger primarily for the stellar surface gravity followed by the planet's radius and mass. This value is expected given that the euclidean distance penalizes large deviations.

In [471]:
# saving the rows associated with the top 10 earth like planets into a dataframe
closest_planets_euc_list = new_exoplanets_filtered_KNN_weighted.loc[closest_planets_euc]
closest_planets_euc_list

,star_number_per_system,orbital_period_day,orbit_semi_major_axis_au,planet_rad_earth_rad,planet_mass_earth_mass,planet_equil_temp_k,stellar_effective_temp_k,stellar_rad_solar_rad,stellar_mass_solar_mass,stellar_surf_grav,...,spectral_type_KII,spectral_type_KIII,spectral_type_KIV,spectral_type_KV,spectral_type_MIII,spectral_type_MV,spectral_type_SD,spectral_type_T,spectral_type_WD,spectral_type_sdB
planet_name,,,,,,,,,,,,,,,,,,,,,
Kepler-452 b,1.0,7.375332,6.058400,8.150000,3.294107,5.529412,0.985303,1.648928,1.544500,4.445550,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Kepler-1638 b,1.0,4.970071,4.704900,9.350000,4.605677,7.735294,0.994090,1.425000,1.376357,4.206098,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Kepler-51 e,1.0,4.993714,4.725706,10.377172,4.600000,5.689555,0.983021,1.305000,1.440000,4.541055,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Kepler-1606 b,1.0,3.764591,3.839040,10.420000,4.035577,6.795294,0.946188,1.239334,1.372500,4.543631,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Kepler-1701 b,1.0,3.241357,3.409560,10.341552,3.978046,6.511765,0.909607,1.191304,1.300500,4.556486,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Kepler-1126 c,1.0,3.826492,3.840864,7.842500,2.999040,7.194118,1.010036,1.381459,1.349625,4.500237,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Kepler-69 c,1.0,4.646725,4.282463,9.207000,4.435693,6.887395,0.986869,1.423500,1.323750,4.377106,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Kepler-1185 b,1.0,1.999842,2.629400,6.650000,1.448796,8.603922,0.994233,1.378000,1.560600,4.422290,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Kepler-442 b,1.0,2.152254,2.370480,7.360714,1.653236,6.005882,0.781393,0.946794,0.969600,4.663674,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0


---
#### **Interpretation of All Results from KNN Models**
Although the top 5 Earth-Like exoplanets remained identical across both weighted Manhattan and weighted Euclidean distance metrics, three planets within the top twenty differed between the two rankings. This indicates that while the strongest Earth analogs are robust to metric choice, mid-tier candidates (ranks 6–10) are sensitive to how feature deviations are aggregated. There is particuarly increased sensitivity to metric choice in regions of feature space where similarity is less tightly constrained.

The stability of the top five candidates across both metrics suggests that the highest-ranked candidates form a robust well-defined similarity cluster in weighted feature space, while lower-ranked candidates occupy a transitional region where similarity is less tightly constrained and more dependent on metric formulation.

The difference in results between the two distance metrics indicate that the manhattan distance with the KNN Model is better suited to understand how similar each feature combimed compares to Earth. While the euclidean distance with the KNN Model is better suited to understand how similar each feature is to Earth while minimizing as many deviations possible. Therefore, rather than identifying a single superior metric, the comparison highlights complementary perspectives on planetary similarity.

-----

# **Experiment #1: Baseline Ranking Comparison**
The purpose of this experiment is to show that our proposed weighted Earth-like similarity ranking provides more meaningful results than simpler ranking approaches.

Please compare your current weighted ranking method with a few simpler baseline methods using the same final cleaned dataset and the same Earth reference row.

### Preparing Dataset for Experiment #1 Unweighted Baseline KNN Models #3 and #4

In [472]:
# copy dataset for experiment #1 for unweighted baseline KNN Models #3 and #4
experiment_1_baseline = new_exoplanets_filtered4.copy()
experiment_1_baseline

,planet_name,star_number_per_system,spectral_type,orbital_period_day,orbit_semi_major_axis_au,planet_rad_earth_rad,planet_mass_earth_mass,planet_equil_temp_k,stellar_effective_temp_k,stellar_rad_solar_rad,stellar_mass_solar_mass,stellar_surf_grav,stellar_luminosity_solar_lum,planet_orbital_velocity,habitable_zone_main_seq
0,11 Com b,2.0,GIII,324.620000,1.226000,61.636581,5505.066162,653.137165,4808.000000,13.760000,2.090000,2.380000,90.778824,1.305879,0
1,11 UMi b,1.0,KIII,516.219985,1.526667,57.057421,4684.814200,728.367922,4276.500000,26.935000,2.780000,1.765000,217.709668,1.349663,0
2,14 And b,1.0,KIII,186.300000,0.761667,30.026230,1224.550434,756.725320,4850.500000,11.275000,1.780000,2.590000,63.134826,1.528982,0
3,14 Her b,1.0,KV,1766.378417,2.814750,42.726171,2559.472162,127.963437,5296.985000,0.999085,0.904000,4.418006,0.705033,0.566812,0
4,16 Cyg B b,3.0,GV,799.375000,1.662833,20.176910,533.514528,191.413504,5728.594000,1.129135,1.016599,4.342293,1.231895,0.782034,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5414,ups And b,2.0,FV,4.616229,0.058895,13.205018,219.960419,1303.179545,6137.820000,1.614742,1.276049,4.161529,3.320113,4.655553,0
5415,ups And c,2.0,FV,240.728533,0.827712,21.840560,629.595000,346.443928,6117.093333,1.614742,1.301399,4.148705,3.275493,1.254124,0
5416,ups And d,2.0,FV,1285.346167,2.528382,31.047562,1313.220000,198.221771,6117.093333,1.614742,1.301399,4.148705,3.275493,0.717561,0
5417,ups Leo b,1.0,GIII,385.200000,1.180000,11.410451,162.092488,604.668957,4836.000000,11.220000,1.480000,2.460000,61.776135,1.120121,0


### Ensure all features are normalized in terms of Earth

In [473]:
# Normalize the orbital period column
experiment_1_baseline['orbital_period_day'] = experiment_1_baseline['orbital_period_day'] / 365.26

# Normalize the planet equilibrium temperature
experiment_1_baseline['planet_equil_temp_k'] = experiment_1_baseline['planet_equil_temp_k'] / 255.0

# Normalize the stellar effective temperature
experiment_1_baseline['stellar_effective_temp_k'] = experiment_1_baseline['stellar_effective_temp_k'] / 5772.0

### Creating target row for Earth

In [474]:
# creating a target row called Earth which all the other rows will be compared to (similarity search)
earth = pd.DataFrame({'planet_name': ['Earth'],
                      'star_number_per_system': [1.0],
                      'orbital_period_day': [1.0],
                      'orbit_semi_major_axis_au':[1.0],
                      'planet_rad_earth_rad': [1.0],
                      'planet_mass_earth_mass': [1.0],
                      'planet_equil_temp_k': [1.0],
                      'spectral_type': ['GV'],
                      'stellar_effective_temp_k': [1.0],
                      'stellar_rad_solar_rad': [1.0],
                      'stellar_mass_solar_mass': [1.0],
                      'stellar_surf_grav': [1.0],
                      'stellar_luminosity_solar_lum': [1.0],
                      'planet_orbital_velocity': [1.0],
                      'habitable_zone_main_seq': [1]})

### Setting planet name as the index (since planet name is the observation)

In [475]:
# set planet name as index for earth row
earth.set_index('planet_name', inplace=True)

# setting the planet_name as the index
experiment_1_baseline.set_index('planet_name', inplace=True)

### Encoding Categorical Columns

In [476]:
# Combine both for fitting the OneHotEncoder to prevent unseen label errors
combined_spectral_type = pd.concat([experiment_1_baseline['spectral_type'], earth['spectral_type']], ignore_index=True)

# Ensure combined_spectral_type is a DataFrame with 1 column
combined_spectral_type_df = pd.DataFrame(combined_spectral_type, columns=['spectral_type'])

# Fit the OneHotEncoder for categorical columns
encoder = OneHotEncoder(sparse_output=False, handle_unknown='ignore')
encoder.fit(combined_spectral_type_df)

# Transform both the original cleaned dataset and the earth target row dataset
experiment_1_baseline_encoded = encoder.transform(experiment_1_baseline[['spectral_type']])
earth_encoded = encoder.transform(earth[['spectral_type']])

# Generate column names for the encoded columns
encoded_columns = encoder.get_feature_names_out(['spectral_type'])

# Convert to DataFrame and ensure indices match
experiment_1_baseline_encoded = pd.DataFrame(
    experiment_1_baseline_encoded,
    columns=encoded_columns,
    index=experiment_1_baseline.index
)
earth_encoded = pd.DataFrame(
    earth_encoded,
    columns=encoded_columns,
    index=earth.index
)

# Drop orignal spectral_type column since we have generated encoded columns
experiment_1_baseline = experiment_1_baseline.drop(columns=['spectral_type'])
earth = earth.drop(columns=['spectral_type'])

# Add encoded columns back into original cleaned dataset and earth
experiment_1_baseline = pd.concat([experiment_1_baseline, experiment_1_baseline_encoded], axis=1)
earth = pd.concat([earth, earth_encoded], axis=1)

In [477]:
experiment_1_baseline.head()

,star_number_per_system,orbital_period_day,orbit_semi_major_axis_au,planet_rad_earth_rad,planet_mass_earth_mass,planet_equil_temp_k,stellar_effective_temp_k,stellar_rad_solar_rad,stellar_mass_solar_mass,stellar_surf_grav,...,spectral_type_KII,spectral_type_KIII,spectral_type_KIV,spectral_type_KV,spectral_type_MIII,spectral_type_MV,spectral_type_SD,spectral_type_T,spectral_type_WD,spectral_type_sdB
planet_name,,,,,,,,,,,,,,,,,,,,,
11 Com b,2.0,0.888737,1.226000,61.636581,5505.066162,2.561322,0.832987,13.760000,2.090000,2.380000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11 UMi b,1.0,1.413295,1.526667,57.057421,4684.814200,2.856345,0.740904,26.935000,2.780000,1.765000,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14 And b,1.0,0.510048,0.761667,30.026230,1224.550434,2.967550,0.840350,11.275000,1.780000,2.590000,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14 Her b,1.0,4.835948,2.814750,42.726171,2559.472162,0.501817,0.917704,0.999085,0.904000,4.418006,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
16 Cyg B b,3.0,2.188510,1.662833,20.176910,533.514528,0.750641,0.992480,1.129135,1.016599,4.342293,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0


In [478]:
earth.head()

,star_number_per_system,orbital_period_day,orbit_semi_major_axis_au,planet_rad_earth_rad,planet_mass_earth_mass,planet_equil_temp_k,stellar_effective_temp_k,stellar_rad_solar_rad,stellar_mass_solar_mass,stellar_surf_grav,...,spectral_type_KII,spectral_type_KIII,spectral_type_KIV,spectral_type_KV,spectral_type_MIII,spectral_type_MV,spectral_type_SD,spectral_type_T,spectral_type_WD,spectral_type_sdB
planet_name,,,,,,,,,,,,,,,,,,,,,
Earth,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0


In [479]:
# copy of dataset for experiment #3
experiment_3 = experiment_1_baseline.copy()
experiment_3

,star_number_per_system,orbital_period_day,orbit_semi_major_axis_au,planet_rad_earth_rad,planet_mass_earth_mass,planet_equil_temp_k,stellar_effective_temp_k,stellar_rad_solar_rad,stellar_mass_solar_mass,stellar_surf_grav,...,spectral_type_KII,spectral_type_KIII,spectral_type_KIV,spectral_type_KV,spectral_type_MIII,spectral_type_MV,spectral_type_SD,spectral_type_T,spectral_type_WD,spectral_type_sdB
planet_name,,,,,,,,,,,,,,,,,,,,,
11 Com b,2.0,0.888737,1.226000,61.636581,5505.066162,2.561322,0.832987,13.760000,2.090000,2.380000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11 UMi b,1.0,1.413295,1.526667,57.057421,4684.814200,2.856345,0.740904,26.935000,2.780000,1.765000,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14 And b,1.0,0.510048,0.761667,30.026230,1224.550434,2.967550,0.840350,11.275000,1.780000,2.590000,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14 Her b,1.0,4.835948,2.814750,42.726171,2559.472162,0.501817,0.917704,0.999085,0.904000,4.418006,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
16 Cyg B b,3.0,2.188510,1.662833,20.176910,533.514528,0.750641,0.992480,1.129135,1.016599,4.342293,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ups And b,2.0,0.012638,0.058895,13.205018,219.960419,5.110508,1.063378,1.614742,1.276049,4.161529,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ups And c,2.0,0.659061,0.827712,21.840560,629.595000,1.358604,1.059787,1.614742,1.301399,4.148705,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ups And d,2.0,3.518990,2.528382,31.047562,1313.220000,0.777340,1.059787,1.614742,1.301399,4.148705,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0


In [480]:
# copy of earth dataset for experiment #3
earth_3 = earth.copy()
earth_3

,star_number_per_system,orbital_period_day,orbit_semi_major_axis_au,planet_rad_earth_rad,planet_mass_earth_mass,planet_equil_temp_k,stellar_effective_temp_k,stellar_rad_solar_rad,stellar_mass_solar_mass,stellar_surf_grav,...,spectral_type_KII,spectral_type_KIII,spectral_type_KIV,spectral_type_KV,spectral_type_MIII,spectral_type_MV,spectral_type_SD,spectral_type_T,spectral_type_WD,spectral_type_sdB
planet_name,,,,,,,,,,,,,,,,,,,,,
Earth,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0


### No weights applied

In [481]:
# no weights applied (all weights = 1.0)
weights = {
    'star_number_per_system': 1.0,
    'orbital_period_day': 1.0,
    'orbit_semi_major_axis_au': 1.0,
    'planet_rad_earth_rad': 1.0,
    'planet_mass_earth_mass': 1.0,
    'planet_equil_temp_k': 1.0,
    'stellar_effective_temp_k': 1.0,
    'stellar_rad_solar_rad': 1.0,
    'stellar_mass_solar_mass': 1.0,
    'stellar_surf_grav': 1.0,
    'stellar_luminosity_solar_lum': 1.0,
    'planet_orbital_velocity': 1.0,
    'spectral_type_AIII': 1.0,
    'spectral_type_AIV': 1.0,
    'spectral_type_AV': 1.0,
    'spectral_type_BIV': 1.0,
    'spectral_type_BV': 1.0,
    'spectral_type_FIV': 1.0,
    'spectral_type_FV': 1.0,
    'spectral_type_GII': 1.0,
    'spectral_type_GIII': 1.0,
    'spectral_type_GIV': 1.0,
    'spectral_type_GV': 1.0,
    'spectral_type_KII': 1.0,
    'spectral_type_KIII': 1.0,
    'spectral_type_KIV': 1.0,
    'spectral_type_KV': 1.0,
    'spectral_type_MIII': 1.0,
    'spectral_type_MV': 1.0,
    'spectral_type_SD': 1.0,
    'spectral_type_T': 1.0,
    'spectral_type_WD': 1.0,
    'spectral_type_sdB': 1.0,
    'habitable_zone_main_seq': 1.0,
}

# Apply weights (note: all weights = 1.0)
for col in experiment_1_baseline.columns:
    weight = weights.get(col, 1.0)
    experiment_1_baseline[col] *= weight
    earth[col] *= weight

In [482]:
experiment_1_baseline.head()

,star_number_per_system,orbital_period_day,orbit_semi_major_axis_au,planet_rad_earth_rad,planet_mass_earth_mass,planet_equil_temp_k,stellar_effective_temp_k,stellar_rad_solar_rad,stellar_mass_solar_mass,stellar_surf_grav,...,spectral_type_KII,spectral_type_KIII,spectral_type_KIV,spectral_type_KV,spectral_type_MIII,spectral_type_MV,spectral_type_SD,spectral_type_T,spectral_type_WD,spectral_type_sdB
planet_name,,,,,,,,,,,,,,,,,,,,,
11 Com b,2.0,0.888737,1.226000,61.636581,5505.066162,2.561322,0.832987,13.760000,2.090000,2.380000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11 UMi b,1.0,1.413295,1.526667,57.057421,4684.814200,2.856345,0.740904,26.935000,2.780000,1.765000,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14 And b,1.0,0.510048,0.761667,30.026230,1224.550434,2.967550,0.840350,11.275000,1.780000,2.590000,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14 Her b,1.0,4.835948,2.814750,42.726171,2559.472162,0.501817,0.917704,0.999085,0.904000,4.418006,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
16 Cyg B b,3.0,2.188510,1.662833,20.176910,533.514528,0.750641,0.992480,1.129135,1.016599,4.342293,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0


In [483]:
earth.head()

,star_number_per_system,orbital_period_day,orbit_semi_major_axis_au,planet_rad_earth_rad,planet_mass_earth_mass,planet_equil_temp_k,stellar_effective_temp_k,stellar_rad_solar_rad,stellar_mass_solar_mass,stellar_surf_grav,...,spectral_type_KII,spectral_type_KIII,spectral_type_KIV,spectral_type_KV,spectral_type_MIII,spectral_type_MV,spectral_type_SD,spectral_type_T,spectral_type_WD,spectral_type_sdB
planet_name,,,,,,,,,,,,,,,,,,,,,
Earth,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0


## **Experiment #1 Baseline Unweighted KNN Manhattan Distance Model #3**

In [484]:
# Fit Nearest Neighbors model with 10 closest neighbors using minkowski distance where p = 1 (manhattan distance)
nbrs = NearestNeighbors(n_neighbors=10, metric='minkowski', p=1).fit(experiment_1_baseline)

# Find the top 10 most similar rows
distances, indices = nbrs.kneighbors(earth)

# Retrieve the 10 closest planet names
closest_planets_man2 = experiment_1_baseline.index[indices[0]].tolist()
closest_distances_man2 = distances[0].tolist()

# Print the results
print("Top 10 most similar planets:")
for i in range(10):
    print(f"{i+1}. {closest_planets_man2[i]} (Distance: {closest_distances_man2[i]:.4f})")

Top 10 most similar planets:
1. Kepler-452 b (Distance: 6.7993)
2. Kepler-1185 b (Distance: 7.7585)
3. Kepler-132 e (Distance: 8.4888)
4. Kepler-1126 c (Distance: 8.5760)
5. Kepler-384 c (Distance: 8.7051)
6. Kepler-1638 b (Distance: 8.8194)
7. Kepler-1253 b (Distance: 8.8426)
8. Kepler-1965 b (Distance: 8.9975)
9. Kepler-1440 b (Distance: 9.0092)
10. Kepler-1605 b (Distance: 9.0991)


## **Experiment #1 Baseline Unweighted KNN Euclidean Distance Model #4**

In [485]:
# Fit Nearest Neighbors model with 10 closest neighbors using minkowski distance where p = 2 (euclidean distance)
nbrs = NearestNeighbors(n_neighbors=10, metric='minkowski', p=2).fit(experiment_1_baseline)

# Find the top 10 most similar rows
distances, indices = nbrs.kneighbors(earth)

# Retrieve the 10 closest planet names
closest_planets_euc2 = experiment_1_baseline.index[indices[0]].tolist()
closest_distances_euc2 = distances[0].tolist()

# Print the results
print("Top 10 most similar planets:")
for i in range(10):
    print(f"{i+1}. {closest_planets_euc2[i]} (Distance: {closest_distances_euc2[i]:.4f})")

Top 10 most similar planets:
1. Kepler-1185 b (Distance: 3.7907)
2. Kepler-1253 b (Distance: 3.8157)
3. Kepler-132 e (Distance: 3.8466)
4. Kepler-384 c (Distance: 3.8933)
5. Kepler-130 d (Distance: 3.9603)
6. Kepler-1440 b (Distance: 3.9850)
7. Kepler-1498 b (Distance: 3.9960)
8. Kepler-1441 b (Distance: 4.0444)
9. Kepler-1965 b (Distance: 4.1045)
10. Kepler-1620 b (Distance: 4.1106)


In [486]:
# seeing where kepler-452 b is ranked for Baseline Unweighted KNN Euclidean Distance Model #4
all_distances, all_indices = nbrs.kneighbors(earth, n_neighbors=len(experiment_1_baseline))

# Map indices to names
all_planets = experiment_1_baseline.index[all_indices[0]]

# enter name of specifc planet to check its ranking
planet_to_check = 'Kepler-452 b'

# Find rank of Kepler-452 b
if planet_to_check in all_planets:
    rank = list(all_planets).index(planet_to_check) + 1
    distance = all_distances[0][rank-1]
    print(f"{planet_to_check} is ranked #{rank} overall with distance {distance:.4f}")
else:
    print(f"{planet_to_check} not found in dataset.")

Kepler-452 b is ranked #15 overall with distance 4.1916


In [487]:
# viewing the row for kepler-452 b
experiment_1_baseline.loc['Kepler-452 b']

,Kepler-452 b
star_number_per_system,1.000000
orbital_period_day,1.053619
orbit_semi_major_axis_au,1.009733
planet_rad_earth_rad,1.630000
planet_mass_earth_mass,3.294107
planet_equil_temp_k,0.921569
stellar_effective_temp_k,0.985303
stellar_rad_solar_rad,1.099285
stellar_mass_solar_mass,1.029667
stellar_surf_grav,4.445550


In [488]:
experiment_1_baseline.loc['Kepler-1185 b']

,Kepler-1185 b
star_number_per_system,1.000000
orbital_period_day,0.285692
orbit_semi_major_axis_au,0.438233
planet_rad_earth_rad,1.330000
planet_mass_earth_mass,1.448796
planet_equil_temp_k,1.433987
stellar_effective_temp_k,0.994233
stellar_rad_solar_rad,0.918667
stellar_mass_solar_mass,1.040400
stellar_surf_grav,4.422290


### Preparing Dataset for Experiment #1 Unweighted Baseline Habitable Zone Filtering KNN Models #5 and #6

In [489]:
# copy dataset for experiment #1 for unweighted baseline Habitable Zone filtering KNN Model #5
experiment_1_baseline_habitable_zone = experiment_1_baseline.copy()
experiment_1_baseline_habitable_zone

,star_number_per_system,orbital_period_day,orbit_semi_major_axis_au,planet_rad_earth_rad,planet_mass_earth_mass,planet_equil_temp_k,stellar_effective_temp_k,stellar_rad_solar_rad,stellar_mass_solar_mass,stellar_surf_grav,...,spectral_type_KII,spectral_type_KIII,spectral_type_KIV,spectral_type_KV,spectral_type_MIII,spectral_type_MV,spectral_type_SD,spectral_type_T,spectral_type_WD,spectral_type_sdB
planet_name,,,,,,,,,,,,,,,,,,,,,
11 Com b,2.0,0.888737,1.226000,61.636581,5505.066162,2.561322,0.832987,13.760000,2.090000,2.380000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11 UMi b,1.0,1.413295,1.526667,57.057421,4684.814200,2.856345,0.740904,26.935000,2.780000,1.765000,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14 And b,1.0,0.510048,0.761667,30.026230,1224.550434,2.967550,0.840350,11.275000,1.780000,2.590000,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14 Her b,1.0,4.835948,2.814750,42.726171,2559.472162,0.501817,0.917704,0.999085,0.904000,4.418006,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
16 Cyg B b,3.0,2.188510,1.662833,20.176910,533.514528,0.750641,0.992480,1.129135,1.016599,4.342293,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ups And b,2.0,0.012638,0.058895,13.205018,219.960419,5.110508,1.063378,1.614742,1.276049,4.161529,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ups And c,2.0,0.659061,0.827712,21.840560,629.595000,1.358604,1.059787,1.614742,1.301399,4.148705,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ups And d,2.0,3.518990,2.528382,31.047562,1313.220000,0.777340,1.059787,1.614742,1.301399,4.148705,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0


In [490]:
# fitlering dataset for rows where only habitable zone = 1
experiment_1_baseline_habitable_zone = experiment_1_baseline_habitable_zone[experiment_1_baseline_habitable_zone['habitable_zone_main_seq'] == 1]
experiment_1_baseline_habitable_zone

,star_number_per_system,orbital_period_day,orbit_semi_major_axis_au,planet_rad_earth_rad,planet_mass_earth_mass,planet_equil_temp_k,stellar_effective_temp_k,stellar_rad_solar_rad,stellar_mass_solar_mass,stellar_surf_grav,...,spectral_type_KII,spectral_type_KIII,spectral_type_KIV,spectral_type_KV,spectral_type_MIII,spectral_type_MV,spectral_type_SD,spectral_type_T,spectral_type_WD,spectral_type_sdB
planet_name,,,,,,,,,,,,,,,,,,,,,
55 Cnc f,2.0,0.713961,0.781513,6.344191,47.529849,0.925168,0.908026,0.963067,0.924286,4.412356,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
AU Mic e,1.0,0.091031,0.170681,4.301580,21.100000,1.277392,0.634962,0.820000,0.600000,4.520000,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
BD+49 828 b,1.0,7.090839,4.200000,19.718599,508.500000,1.057325,0.856376,7.600000,1.520000,2.850000,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
BD-11 4672 c,1.0,0.203143,0.300000,3.696464,15.370000,1.055934,0.788288,0.639000,0.651000,4.642000,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
EPIC 212737443 c,1.0,0.179461,0.280000,2.690000,6.554346,1.239216,0.811504,0.673000,0.690000,4.622000,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TOI-4633 c,2.0,0.744523,0.847000,3.200000,123.000000,1.026873,1.004851,1.050000,1.100000,4.436836,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
TOI-500 e,1.0,0.167826,0.275206,3.659440,15.050000,1.108166,0.769231,0.678000,0.740000,4.618000,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
TOI-544 c,1.0,0.137132,0.228093,4.340406,21.500000,1.095610,0.722280,0.623000,0.631000,4.680000,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0


In [491]:
# removing all features except planets radius, planet mass, orbital semi major axis, and planet equilibrium temeprature for experiment_1_baseline_habitable_zone dataframe
experiment_1_baseline_habitable_zone = experiment_1_baseline_habitable_zone[['planet_rad_earth_rad', 'planet_mass_earth_mass', 'orbit_semi_major_axis_au', 'planet_equil_temp_k']]
experiment_1_baseline_habitable_zone

,planet_rad_earth_rad,planet_mass_earth_mass,orbit_semi_major_axis_au,planet_equil_temp_k
planet_name,,,,
55 Cnc f,6.344191,47.529849,0.781513,0.925168
AU Mic e,4.301580,21.100000,0.170681,1.277392
BD+49 828 b,19.718599,508.500000,4.200000,1.057325
BD-11 4672 c,3.696464,15.370000,0.300000,1.055934
EPIC 212737443 c,2.690000,6.554346,0.280000,1.239216
...,...,...,...,...
TOI-4633 c,3.200000,123.000000,0.847000,1.026873
TOI-500 e,3.659440,15.050000,0.275206,1.108166
TOI-544 c,4.340406,21.500000,0.228093,1.095610


In [492]:
# removing all features except planets radius, planet mass, orbital semi major axis, and planet equilibrium temeprature for earth dataframe
earth_habitable_zone = earth[['planet_rad_earth_rad', 'planet_mass_earth_mass', 'orbit_semi_major_axis_au', 'planet_equil_temp_k']]
earth_habitable_zone

,planet_rad_earth_rad,planet_mass_earth_mass,orbit_semi_major_axis_au,planet_equil_temp_k
planet_name,,,,
Earth,1.0,1.0,1.0,1.0


## **Experiment #1 Baseline Unweighted Baseline Habitable Zone Filtering Manhattan Distance KNN Model #5**

In [493]:
# Fit Nearest Neighbors model with 10 closest neighbors using minkowski distance where p = 1 (manhattan distance)
nbrs = NearestNeighbors(n_neighbors=10, metric='minkowski', p=1).fit(experiment_1_baseline_habitable_zone)

# Find the top 10 most similar rows
distances, indices = nbrs.kneighbors(earth_habitable_zone)

# Retrieve the 10 closest planet names
closest_planets_man3 = experiment_1_baseline_habitable_zone.index[indices[0]].tolist()
closest_distances_man3 = distances[0].tolist()

# Print the results
print("Top 10 most similar planets:")
for i in range(10):
    print(f"{i+1}. {closest_planets_man3[i]} (Distance: {closest_distances_man3[i]:.4f})")

Top 10 most similar planets:
1. Kepler-438 b (Distance: 0.9746)
2. Kepler-296 e (Distance: 1.7012)
3. Kepler-442 b (Distance: 1.7313)
4. Kepler-395 c (Distance: 1.7369)
5. Kepler-138 e (Distance: 1.8670)
6. Kepler-452 b (Distance: 3.0123)
7. Kepler-1410 b (Distance: 3.6892)
8. Kepler-1544 b (Distance: 4.2228)
9. Kepler-1701 b (Distance: 4.5634)
10. Kepler-1606 b (Distance: 4.6123)


## **Experiment #1 Baseline Unweighted Baseline Habitable Zone Filtering Euclidean Distance KNN Model #6**

In [494]:
# Fit Nearest Neighbors model with 10 closest neighbors using minkowski distance where p = 2 (euclidean distance)
nbrs = NearestNeighbors(n_neighbors=10, metric='minkowski', p=2).fit(experiment_1_baseline_habitable_zone)

# Find the top 10 most similar rows
distances, indices = nbrs.kneighbors(earth_habitable_zone)

# Retrieve the 10 closest planet names
closest_planets_euc3 = experiment_1_baseline_habitable_zone.index[indices[0]].tolist()
closest_distances_euc3 = distances[0].tolist()

# Print the results
print("Top 10 most similar planets:")
for i in range(10):
    print(f"{i+1}. {closest_planets_euc3[i]} (Distance: {closest_distances_euc3[i]:.4f})")

Top 10 most similar planets:
1. Kepler-438 b (Distance: 0.8386)
2. Kepler-442 b (Distance: 1.0078)
3. Kepler-395 c (Distance: 1.0078)
4. Kepler-296 e (Distance: 1.0208)
5. Kepler-138 e (Distance: 1.0622)
6. Kepler-452 b (Distance: 2.3804)
7. Kepler-1410 b (Distance: 2.4949)
8. Kepler-1544 b (Distance: 3.1276)
9. Kepler-1701 b (Distance: 3.1943)
10. Kepler-1450 b (Distance: 3.2306)


----------------

# **Experiment #2: Ablation Study**
After the baseline comparison, please perform an ablation study. The purpose of this experiment is to identify which feature groups are most important for the Earth-like ranking.

In this experiment, you will run the same ranking method multiple times, but each time you will remove one group of features and observe how the top 10 rankings change.

Please use the current weighted Manhattan and weighted Euclidean ranking methods as the full model.

## **Experiment #2 Ablation KNN Model (Full Model) #7 and #8**

In [495]:
# already complete

### Preparing Dataset for Experiment #2 Ablation (No planetary features) KNN Models #9 and #10

In [496]:
# creating copy of experiment_1_baseline dataset
experiment_2_ablation = experiment_1_baseline.copy()
experiment_2_ablation

,star_number_per_system,orbital_period_day,orbit_semi_major_axis_au,planet_rad_earth_rad,planet_mass_earth_mass,planet_equil_temp_k,stellar_effective_temp_k,stellar_rad_solar_rad,stellar_mass_solar_mass,stellar_surf_grav,...,spectral_type_KII,spectral_type_KIII,spectral_type_KIV,spectral_type_KV,spectral_type_MIII,spectral_type_MV,spectral_type_SD,spectral_type_T,spectral_type_WD,spectral_type_sdB
planet_name,,,,,,,,,,,,,,,,,,,,,
11 Com b,2.0,0.888737,1.226000,61.636581,5505.066162,2.561322,0.832987,13.760000,2.090000,2.380000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11 UMi b,1.0,1.413295,1.526667,57.057421,4684.814200,2.856345,0.740904,26.935000,2.780000,1.765000,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14 And b,1.0,0.510048,0.761667,30.026230,1224.550434,2.967550,0.840350,11.275000,1.780000,2.590000,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14 Her b,1.0,4.835948,2.814750,42.726171,2559.472162,0.501817,0.917704,0.999085,0.904000,4.418006,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
16 Cyg B b,3.0,2.188510,1.662833,20.176910,533.514528,0.750641,0.992480,1.129135,1.016599,4.342293,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ups And b,2.0,0.012638,0.058895,13.205018,219.960419,5.110508,1.063378,1.614742,1.276049,4.161529,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ups And c,2.0,0.659061,0.827712,21.840560,629.595000,1.358604,1.059787,1.614742,1.301399,4.148705,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ups And d,2.0,3.518990,2.528382,31.047562,1313.220000,0.777340,1.059787,1.614742,1.301399,4.148705,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0


In [497]:
# removing all planetary features from the experiment_2_ablation dataframe
experiment_2_ablation_no_planet = experiment_2_ablation.drop(columns=['planet_rad_earth_rad', 'planet_mass_earth_mass',
                                                                      'orbit_semi_major_axis_au', 'planet_equil_temp_k', 'planet_orbital_velocity'])
experiment_2_ablation_no_planet

,star_number_per_system,orbital_period_day,stellar_effective_temp_k,stellar_rad_solar_rad,stellar_mass_solar_mass,stellar_surf_grav,stellar_luminosity_solar_lum,habitable_zone_main_seq,spectral_type_AIII,spectral_type_AIV,...,spectral_type_KII,spectral_type_KIII,spectral_type_KIV,spectral_type_KV,spectral_type_MIII,spectral_type_MV,spectral_type_SD,spectral_type_T,spectral_type_WD,spectral_type_sdB
planet_name,,,,,,,,,,,,,,,,,,,,,
11 Com b,2.0,0.888737,0.832987,13.760000,2.090000,2.380000,90.778824,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11 UMi b,1.0,1.413295,0.740904,26.935000,2.780000,1.765000,217.709668,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14 And b,1.0,0.510048,0.840350,11.275000,1.780000,2.590000,63.134826,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14 Her b,1.0,4.835948,0.917704,0.999085,0.904000,4.418006,0.705033,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
16 Cyg B b,3.0,2.188510,0.992480,1.129135,1.016599,4.342293,1.231895,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ups And b,2.0,0.012638,1.063378,1.614742,1.276049,4.161529,3.320113,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ups And c,2.0,0.659061,1.059787,1.614742,1.301399,4.148705,3.275493,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ups And d,2.0,3.518990,1.059787,1.614742,1.301399,4.148705,3.275493,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0


In [498]:
# removing all planetary features from earth dataframe
earth_no_planet = earth.drop(columns=['planet_rad_earth_rad', 'planet_mass_earth_mass', 'orbit_semi_major_axis_au', 'planet_equil_temp_k', 'planet_orbital_velocity'])
earth_no_planet

,star_number_per_system,orbital_period_day,stellar_effective_temp_k,stellar_rad_solar_rad,stellar_mass_solar_mass,stellar_surf_grav,stellar_luminosity_solar_lum,habitable_zone_main_seq,spectral_type_AIII,spectral_type_AIV,...,spectral_type_KII,spectral_type_KIII,spectral_type_KIV,spectral_type_KV,spectral_type_MIII,spectral_type_MV,spectral_type_SD,spectral_type_T,spectral_type_WD,spectral_type_sdB
planet_name,,,,,,,,,,,,,,,,,,,,,
Earth,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0


## **Experiment #2 Ablation (No planetary features) Manhattan Distance KNN Model #9**

In [499]:
# Fit Nearest Neighbors model with 10 closest neighbors using minkowski distance where p = 1 (manhattan distance)
nbrs = NearestNeighbors(n_neighbors=10, metric='minkowski', p=1).fit(experiment_2_ablation_no_planet)

# Find the top 10 most similar rows
distances, indices = nbrs.kneighbors(earth_no_planet)

# Retrieve the 10 closest planet names
closest_planets_man4 = experiment_2_ablation_no_planet.index[indices[0]].tolist()
closest_distances_man4 = distances[0].tolist()

# Print the results
print("Top 10 most similar planets:")
for i in range(10):
    print(f"{i+1}. {closest_planets_man4[i]} (Distance: {closest_distances_man4[i]:.4f})")

Top 10 most similar planets:
1. HD 43197 b (Distance: 3.6984)
2. Kepler-1638 b (Distance: 3.7567)
3. Kepler-452 b (Distance: 3.7770)
4. Kepler-289 e (Distance: 3.7783)
5. Kepler-1625 b (Distance: 3.8063)
6. PH2 b (Distance: 3.8435)
7. Kepler-1634 b (Distance: 3.8917)
8. Kepler-1636 b (Distance: 3.9035)
9. HD 142415 b (Distance: 3.9222)
10. Kepler-1519 b (Distance: 3.9488)


## **Experiment #2 Ablation (No planetary features) Euclidean Distance KNN Model #10**

In [500]:
# Fit Nearest Neighbors model with 10 closest neighbors using minkowski distance where p = 2 (euclidean distance)
nbrs = NearestNeighbors(n_neighbors=10, metric='minkowski', p=2).fit(experiment_2_ablation_no_planet)

# Find the top 10 most similar rows
distances, indices = nbrs.kneighbors(earth_no_planet)

# Retrieve the 10 closest planet names
closest_planets_euc4 = experiment_2_ablation_no_planet.index[indices[0]].tolist()
closest_distances_euc4 = distances[0].tolist()

# Print the results
print("Top 10 most similar planets:")
for i in range(10):
    print(f"{i+1}. {closest_planets_euc4[i]} (Distance: {closest_distances_euc4[i]:.4f})")

Top 10 most similar planets:
1. Kepler-1625 b (Distance: 3.2208)
2. Kepler-1638 b (Distance: 3.2230)
3. Kepler-784 b (Distance: 3.2285)
4. Kepler-1570 b (Distance: 3.2712)
5. Kepler-1929 b (Distance: 3.2985)
6. Kepler-525 b (Distance: 3.3029)
7. Kepler-638 b (Distance: 3.3036)
8. HD 43197 b (Distance: 3.3176)
9. HD 44219 b (Distance: 3.3178)
10. Kepler-806 b (Distance: 3.3239)


### Preparing Dataset for Experiment #2 Ablation (No stellar features - Partial) KNN Models #11 and #12

In [501]:
# removing all stellar features except for spectral type from the experiment_2_ablation dataframe
experiment_2_ablation_no_stellar = experiment_2_ablation.drop(columns=['stellar_effective_temp_k', 'stellar_rad_solar_rad', 'stellar_mass_solar_mass',
                                                                       'stellar_surf_grav', 'stellar_luminosity_solar_lum'])
experiment_2_ablation_no_stellar

,star_number_per_system,orbital_period_day,orbit_semi_major_axis_au,planet_rad_earth_rad,planet_mass_earth_mass,planet_equil_temp_k,planet_orbital_velocity,habitable_zone_main_seq,spectral_type_AIII,spectral_type_AIV,...,spectral_type_KII,spectral_type_KIII,spectral_type_KIV,spectral_type_KV,spectral_type_MIII,spectral_type_MV,spectral_type_SD,spectral_type_T,spectral_type_WD,spectral_type_sdB
planet_name,,,,,,,,,,,,,,,,,,,,,
11 Com b,2.0,0.888737,1.226000,61.636581,5505.066162,2.561322,1.305879,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11 UMi b,1.0,1.413295,1.526667,57.057421,4684.814200,2.856345,1.349663,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14 And b,1.0,0.510048,0.761667,30.026230,1224.550434,2.967550,1.528982,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14 Her b,1.0,4.835948,2.814750,42.726171,2559.472162,0.501817,0.566812,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
16 Cyg B b,3.0,2.188510,1.662833,20.176910,533.514528,0.750641,0.782034,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ups And b,2.0,0.012638,0.058895,13.205018,219.960419,5.110508,4.655553,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ups And c,2.0,0.659061,0.827712,21.840560,629.595000,1.358604,1.254124,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ups And d,2.0,3.518990,2.528382,31.047562,1313.220000,0.777340,0.717561,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0


In [502]:
# removing all stellar features except for spectral type from earth dataframe
earth_no_stellar = earth.drop(columns=['stellar_effective_temp_k', 'stellar_rad_solar_rad', 'stellar_mass_solar_mass',
                                                                       'stellar_surf_grav', 'stellar_luminosity_solar_lum'])
earth_no_stellar

,star_number_per_system,orbital_period_day,orbit_semi_major_axis_au,planet_rad_earth_rad,planet_mass_earth_mass,planet_equil_temp_k,planet_orbital_velocity,habitable_zone_main_seq,spectral_type_AIII,spectral_type_AIV,...,spectral_type_KII,spectral_type_KIII,spectral_type_KIV,spectral_type_KV,spectral_type_MIII,spectral_type_MV,spectral_type_SD,spectral_type_T,spectral_type_WD,spectral_type_sdB
planet_name,,,,,,,,,,,,,,,,,,,,,
Earth,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0


## **Experiment #2 Ablation (No Stellar features - Partial) Manhattan Distance KNN Model #11**

In [503]:
# Fit Nearest Neighbors model with 10 closest neighbors using minkowski distance where p = 1 (manhattan distance)
nbrs = NearestNeighbors(n_neighbors=10, metric='minkowski', p=1).fit(experiment_2_ablation_no_stellar)

# Find the top 10 most similar rows
distances, indices = nbrs.kneighbors(earth_no_stellar)

# Retrieve the 10 closest planet names
closest_planets_man5 = experiment_2_ablation_no_stellar.index[indices[0]].tolist()
closest_distances_man5 = distances[0].tolist()

# Print the results
print("Top 10 most similar planets:")
for i in range(10):
    print(f"{i+1}. {closest_planets_man5[i]} (Distance: {closest_distances_man5[i]:.4f})")

Top 10 most similar planets:
1. Kepler-452 b (Distance: 3.0759)
2. Kepler-1185 b (Distance: 4.0299)
3. Kepler-1605 b (Distance: 4.5805)
4. Kepler-442 b (Distance: 4.7031)
5. Kepler-438 b (Distance: 4.7050)
6. Kepler-132 e (Distance: 4.7608)
7. Kepler-1126 c (Distance: 4.7655)
8. Kepler-384 c (Distance: 4.9006)
9. Kepler-1965 b (Distance: 4.9600)
10. Kepler-186 f (Distance: 5.0085)


## **Experiment #2 Ablation (No Stellar features - Partial) Euclidean Distance KNN Model #12**

In [504]:
#Fit Nearest Neighbors model with 10 closest neighbors using minkowski distance where p = 2 (euclidean distance)
nbrs = NearestNeighbors(n_neighbors=10, metric='minkowski', p=2).fit(experiment_2_ablation_no_stellar)

# Find the top 10 most similar rows
distances, indices = nbrs.kneighbors(earth_no_stellar)

# Retrieve the 10 closest planet names
closest_planets_euc5 = experiment_2_ablation_no_stellar.index[indices[0]].tolist()
closest_distances_euc5 = distances[0].tolist()

# Print the results
print("Top 10 most similar planets:")
for i in range(10):
    print(f"{i+1}. {closest_planets_euc5[i]} (Distance: {closest_distances_euc5[i]:.4f})")

Top 10 most similar planets:
1. Kepler-1185 b (Distance: 1.6178)
2. Kepler-132 e (Distance: 1.8632)
3. Kepler-442 b (Distance: 1.8903)
4. Kepler-186 f (Distance: 1.9865)
5. Kepler-1253 b (Distance: 1.9978)
6. Kepler-1498 b (Distance: 2.0314)
7. Kepler-438 b (Distance: 2.0502)
8. Kepler-384 c (Distance: 2.0774)
9. Kepler-1965 b (Distance: 2.0815)
10. Kepler-138 e (Distance: 2.1101)


### Preparing Dataset for Experiment #2 Ablation (No stellar features - Full) KNN Models #11.5 and #12.5

In [505]:
# removing all stellar features including one hot encoded spctral type features from the experiment_2_ablation dataframe
# so removing the spctral type features from experiment_2_ablation_no_stellar
experiment_2_ablation_no_stellar_full = experiment_2_ablation_no_stellar.drop(columns=[col for col in experiment_2_ablation_no_stellar.columns if col.startswith('spectral_type_')])
experiment_2_ablation_no_stellar_full

,star_number_per_system,orbital_period_day,orbit_semi_major_axis_au,planet_rad_earth_rad,planet_mass_earth_mass,planet_equil_temp_k,planet_orbital_velocity,habitable_zone_main_seq
planet_name,,,,,,,,
11 Com b,2.0,0.888737,1.226000,61.636581,5505.066162,2.561322,1.305879,0.0
11 UMi b,1.0,1.413295,1.526667,57.057421,4684.814200,2.856345,1.349663,0.0
14 And b,1.0,0.510048,0.761667,30.026230,1224.550434,2.967550,1.528982,0.0
14 Her b,1.0,4.835948,2.814750,42.726171,2559.472162,0.501817,0.566812,0.0
16 Cyg B b,3.0,2.188510,1.662833,20.176910,533.514528,0.750641,0.782034,0.0
...,...,...,...,...,...,...,...,...
ups And b,2.0,0.012638,0.058895,13.205018,219.960419,5.110508,4.655553,0.0
ups And c,2.0,0.659061,0.827712,21.840560,629.595000,1.358604,1.254124,0.0
ups And d,2.0,3.518990,2.528382,31.047562,1313.220000,0.777340,0.717561,0.0


In [506]:
# removing all stellar features including one hot encoded spctral type features from the earth dataframe
# so removing the spctral type features from earth_no_stellar
earth_no_stellar_full = earth_no_stellar.drop(columns=[col for col in earth_no_stellar.columns if col.startswith('spectral_type_')])
earth_no_stellar_full

,star_number_per_system,orbital_period_day,orbit_semi_major_axis_au,planet_rad_earth_rad,planet_mass_earth_mass,planet_equil_temp_k,planet_orbital_velocity,habitable_zone_main_seq
planet_name,,,,,,,,
Earth,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0


## **Experiment #2 Ablation (No Stellar features - Full) Manhattan Distance KNN Model #11.5**

In [507]:
# Fit Nearest Neighbors model with 10 closest neighbors using minkowski distance where p = 1 (manhattan distance)
nbrs = NearestNeighbors(n_neighbors=10, metric='minkowski', p=1).fit(experiment_2_ablation_no_stellar_full)

# Find the top 10 most similar rows
distances, indices = nbrs.kneighbors(earth_no_stellar_full)

# Retrieve the 10 closest planet names
closest_planets_man5_5 = experiment_2_ablation_no_stellar_full.index[indices[0]].tolist()
closest_distances_man5_5 = distances[0].tolist()

# Print the results
print("Top 10 most similar planets:")
for i in range(10):
    print(f"{i+1}. {closest_planets_man5_5[i]} (Distance: {closest_distances_man5_5[i]:.4f})")

Top 10 most similar planets:
1. Kepler-442 b (Distance: 2.7031)
2. Kepler-438 b (Distance: 2.7050)
3. Kepler-186 f (Distance: 3.0085)
4. Kepler-452 b (Distance: 3.0759)
5. Kepler-138 e (Distance: 3.4852)
6. Kepler-395 c (Distance: 3.5338)
7. Teegarden's Star d (Distance: 3.6040)
8. Teegarden's Star c (Distance: 3.6612)
9. TOI-700 e (Distance: 3.6827)
10. TOI-700 d (Distance: 3.6995)


## **Experiment #2 Ablation (No Stellar features - Full) Euclidean Distance KNN Model #12.5**

In [508]:
#Fit Nearest Neighbors model with 10 closest neighbors using minkowski distance where p = 2 (euclidean distance)
nbrs = NearestNeighbors(n_neighbors=10, metric='minkowski', p=2).fit(experiment_2_ablation_no_stellar_full)

# Find the top 10 most similar rows
distances, indices = nbrs.kneighbors(earth_no_stellar_full)

# Retrieve the 10 closest planet names
closest_planets_euc5_5 = experiment_2_ablation_no_stellar_full.index[indices[0]].tolist()
closest_distances_euc5_5 = distances[0].tolist()

# Print the results
print("Top 10 most similar planets:")
for i in range(10):
    print(f"{i+1}. {closest_planets_euc5_5[i]} (Distance: {closest_distances_euc5_5[i]:.4f})")

Top 10 most similar planets:
1. Kepler-442 b (Distance: 1.2543)
2. Kepler-186 f (Distance: 1.3951)
3. Kepler-438 b (Distance: 1.4844)
4. Kepler-138 e (Distance: 1.5660)
5. Kepler-1185 b (Distance: 1.6178)
6. Kepler-395 c (Distance: 1.6217)
7. Kepler-1229 b (Distance: 1.6636)
8. Teegarden's Star d (Distance: 1.7041)
9. TOI-700 d (Distance: 1.7071)
10. GJ 1002 c (Distance: 1.7488)


### Preparing Dataset for Experiment #2 Ablation (No orbital features) KNN Models #13 and #14

In [509]:
# removing all orbital features from the experiment_2_ablation dataframe
experiment_2_ablation_no_orbital = experiment_2_ablation.drop(columns=['orbital_period_day', 'orbit_semi_major_axis_au'])
experiment_2_ablation_no_orbital

,star_number_per_system,planet_rad_earth_rad,planet_mass_earth_mass,planet_equil_temp_k,stellar_effective_temp_k,stellar_rad_solar_rad,stellar_mass_solar_mass,stellar_surf_grav,stellar_luminosity_solar_lum,planet_orbital_velocity,...,spectral_type_KII,spectral_type_KIII,spectral_type_KIV,spectral_type_KV,spectral_type_MIII,spectral_type_MV,spectral_type_SD,spectral_type_T,spectral_type_WD,spectral_type_sdB
planet_name,,,,,,,,,,,,,,,,,,,,,
11 Com b,2.0,61.636581,5505.066162,2.561322,0.832987,13.760000,2.090000,2.380000,90.778824,1.305879,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11 UMi b,1.0,57.057421,4684.814200,2.856345,0.740904,26.935000,2.780000,1.765000,217.709668,1.349663,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14 And b,1.0,30.026230,1224.550434,2.967550,0.840350,11.275000,1.780000,2.590000,63.134826,1.528982,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14 Her b,1.0,42.726171,2559.472162,0.501817,0.917704,0.999085,0.904000,4.418006,0.705033,0.566812,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
16 Cyg B b,3.0,20.176910,533.514528,0.750641,0.992480,1.129135,1.016599,4.342293,1.231895,0.782034,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ups And b,2.0,13.205018,219.960419,5.110508,1.063378,1.614742,1.276049,4.161529,3.320113,4.655553,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ups And c,2.0,21.840560,629.595000,1.358604,1.059787,1.614742,1.301399,4.148705,3.275493,1.254124,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ups And d,2.0,31.047562,1313.220000,0.777340,1.059787,1.614742,1.301399,4.148705,3.275493,0.717561,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0


In [510]:
# removing all orbital features from the earth dataframe
earth_no_orbital = earth.drop(columns=['orbital_period_day', 'orbit_semi_major_axis_au'])
earth_no_orbital

,star_number_per_system,planet_rad_earth_rad,planet_mass_earth_mass,planet_equil_temp_k,stellar_effective_temp_k,stellar_rad_solar_rad,stellar_mass_solar_mass,stellar_surf_grav,stellar_luminosity_solar_lum,planet_orbital_velocity,...,spectral_type_KII,spectral_type_KIII,spectral_type_KIV,spectral_type_KV,spectral_type_MIII,spectral_type_MV,spectral_type_SD,spectral_type_T,spectral_type_WD,spectral_type_sdB
planet_name,,,,,,,,,,,,,,,,,,,,,
Earth,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0


## **Experiment #2 Ablation (No Orbital features) Manhattan Distance KNN Model #13**

In [511]:
# Fit Nearest Neighbors model with 10 closest neighbors using minkowski distance where p = 1 (manhattan distance)
nbrs = NearestNeighbors(n_neighbors=10, metric='minkowski', p=1).fit(experiment_2_ablation_no_orbital)

# Find the top 10 most similar rows
distances, indices = nbrs.kneighbors(earth_no_orbital)

# Retrieve the 10 closest planet names
closest_planets_man6 = experiment_2_ablation_no_orbital.index[indices[0]].tolist()
closest_distances_man6 = distances[0].tolist()

# Print the results
print("Top 10 most similar planets:")
for i in range(10):
    print(f"{i+1}. {closest_planets_man6[i]} (Distance: {closest_distances_man6[i]:.4f})")

Top 10 most similar planets:
1. Kepler-1185 b (Distance: 6.4824)
2. Kepler-452 b (Distance: 6.7359)
3. Kepler-384 c (Distance: 7.0647)
4. Kepler-132 e (Distance: 7.2291)
5. Kepler-1965 b (Distance: 7.3424)
6. Kepler-1440 b (Distance: 7.3452)
7. Kepler-1253 b (Distance: 7.3458)
8. Kepler-1505 b (Distance: 7.6164)
9. Kepler-1498 b (Distance: 7.7329)
10. Kepler-1441 b (Distance: 7.7526)


## **Experiment #2 Ablation (No Orbital features) Euclidean Distance KNN Model #14**

In [512]:
#Fit Nearest Neighbors model with 10 closest neighbors using minkowski distance where p = 2 (euclidean distance)
nbrs = NearestNeighbors(n_neighbors=10, metric='minkowski', p=2).fit(experiment_2_ablation_no_orbital)

# Find the top 10 most similar rows
distances, indices = nbrs.kneighbors(earth_no_orbital)

# Retrieve the 10 closest planet names
closest_planets_euc6 = experiment_2_ablation_no_orbital.index[indices[0]].tolist()
closest_distances_euc6 = distances[0].tolist()

# Print the results
print("Top 10 most similar planets:")
for i in range(10):
    print(f"{i+1}. {closest_planets_euc6[i]} (Distance: {closest_distances_euc6[i]:.4f})")

Top 10 most similar planets:
1. Kepler-1253 b (Distance: 3.6649)
2. Kepler-1185 b (Distance: 3.6802)
3. Kepler-384 c (Distance: 3.7157)
4. Kepler-132 e (Distance: 3.7408)
5. Kepler-1440 b (Distance: 3.8064)
6. Kepler-1498 b (Distance: 3.8268)
7. Kepler-130 d (Distance: 3.8365)
8. Kepler-1441 b (Distance: 3.8677)
9. Kepler-1965 b (Distance: 3.9333)
10. Kepler-1505 b (Distance: 3.9847)


### Preparing Dataset for Experiment #2 Ablation (No Spectral Type) KNN Models #15 and #16

In [513]:
# removing all columns that start with spectral_type_ from the experiment_2_ablation dataframe
experiment_2_ablation_no_spec_type = experiment_2_ablation.drop(columns=[col for col in experiment_2_ablation.columns if col.startswith('spectral_type_')])
experiment_2_ablation_no_spec_type

,star_number_per_system,orbital_period_day,orbit_semi_major_axis_au,planet_rad_earth_rad,planet_mass_earth_mass,planet_equil_temp_k,stellar_effective_temp_k,stellar_rad_solar_rad,stellar_mass_solar_mass,stellar_surf_grav,stellar_luminosity_solar_lum,planet_orbital_velocity,habitable_zone_main_seq
planet_name,,,,,,,,,,,,,
11 Com b,2.0,0.888737,1.226000,61.636581,5505.066162,2.561322,0.832987,13.760000,2.090000,2.380000,90.778824,1.305879,0.0
11 UMi b,1.0,1.413295,1.526667,57.057421,4684.814200,2.856345,0.740904,26.935000,2.780000,1.765000,217.709668,1.349663,0.0
14 And b,1.0,0.510048,0.761667,30.026230,1224.550434,2.967550,0.840350,11.275000,1.780000,2.590000,63.134826,1.528982,0.0
14 Her b,1.0,4.835948,2.814750,42.726171,2559.472162,0.501817,0.917704,0.999085,0.904000,4.418006,0.705033,0.566812,0.0
16 Cyg B b,3.0,2.188510,1.662833,20.176910,533.514528,0.750641,0.992480,1.129135,1.016599,4.342293,1.231895,0.782034,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
ups And b,2.0,0.012638,0.058895,13.205018,219.960419,5.110508,1.063378,1.614742,1.276049,4.161529,3.320113,4.655553,0.0
ups And c,2.0,0.659061,0.827712,21.840560,629.595000,1.358604,1.059787,1.614742,1.301399,4.148705,3.275493,1.254124,0.0
ups And d,2.0,3.518990,2.528382,31.047562,1313.220000,0.777340,1.059787,1.614742,1.301399,4.148705,3.275493,0.717561,0.0


In [514]:
# removing all columns that start with spectral_type_ from the earth dataframe
earth_no_spec_type = earth.drop(columns=[col for col in earth.columns if col.startswith('spectral_type_')])
earth_no_spec_type

,star_number_per_system,orbital_period_day,orbit_semi_major_axis_au,planet_rad_earth_rad,planet_mass_earth_mass,planet_equil_temp_k,stellar_effective_temp_k,stellar_rad_solar_rad,stellar_mass_solar_mass,stellar_surf_grav,stellar_luminosity_solar_lum,planet_orbital_velocity,habitable_zone_main_seq
planet_name,,,,,,,,,,,,,
Earth,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0


## **Experiment #2 Ablation (No Spectral Type) Manhattan Distance KNN Model #15**

In [515]:
# Fit Nearest Neighbors model with 10 closest neighbors using minkowski distance where p = 1 (manhattan distance)
nbrs = NearestNeighbors(n_neighbors=10, metric='minkowski', p=1).fit(experiment_2_ablation_no_spec_type)

# Find the top 10 most similar rows
distances, indices = nbrs.kneighbors(earth_no_spec_type)

# Retrieve the 10 closest planet names
closest_planets_man7 = experiment_2_ablation_no_spec_type.index[indices[0]].tolist()
closest_distances_man7 = distances[0].tolist()

# Print the results
print("Top 10 most similar planets:")
for i in range(10):
    print(f"{i+1}. {closest_planets_man7[i]} (Distance: {closest_distances_man7[i]:.4f})")

Top 10 most similar planets:
1. Kepler-452 b (Distance: 6.7993)
2. Kepler-1185 b (Distance: 7.7585)
3. Kepler-442 b (Distance: 8.1599)
4. Kepler-132 e (Distance: 8.4888)
5. Kepler-1126 c (Distance: 8.5760)
6. Kepler-438 b (Distance: 8.6220)
7. Kepler-1620 b (Distance: 8.6520)
8. Kepler-384 c (Distance: 8.7051)
9. Kepler-1638 b (Distance: 8.8194)
10. Kepler-1253 b (Distance: 8.8426)


## **Experiment #2 Ablation (No Spectral Type) Euclidean Distance KNN Model #16**

In [516]:
#Fit Nearest Neighbors model with 10 closest neighbors using minkowski distance where p = 2 (euclidean distance)
nbrs = NearestNeighbors(n_neighbors=10, metric='minkowski', p=2).fit(experiment_2_ablation_no_spec_type)

# Find the top 10 most similar rows
distances, indices = nbrs.kneighbors(earth_no_spec_type)

# Retrieve the 10 closest planet names
closest_planets_euc7 = experiment_2_ablation_no_spec_type.index[indices[0]].tolist()
closest_distances_euc7 = distances[0].tolist()

# Print the results
print("Top 10 most similar planets:")
for i in range(10):
    print(f"{i+1}. {closest_planets_euc7[i]} (Distance: {closest_distances_euc7[i]:.4f})")

Top 10 most similar planets:
1. Kepler-1185 b (Distance: 3.7907)
2. Kepler-1253 b (Distance: 3.8157)
3. Kepler-132 e (Distance: 3.8466)
4. Kepler-1620 b (Distance: 3.8597)
5. Kepler-384 c (Distance: 3.8933)
6. Kepler-130 d (Distance: 3.9603)
7. Kepler-1440 b (Distance: 3.9850)
8. Kepler-1498 b (Distance: 3.9960)
9. Kepler-442 b (Distance: 4.0038)
10. Kepler-1459 b (Distance: 4.0104)


### Preparing Dataset for Experiment #2 Ablation (No Habitable Zone) KNN Models #17 and #18

In [517]:
# removing habitable zone column from the experiment_2_ablation dataframe
experiment_2_ablation_no_hab_zone = experiment_2_ablation.drop(columns=['habitable_zone_main_seq'])
experiment_2_ablation_no_hab_zone

,star_number_per_system,orbital_period_day,orbit_semi_major_axis_au,planet_rad_earth_rad,planet_mass_earth_mass,planet_equil_temp_k,stellar_effective_temp_k,stellar_rad_solar_rad,stellar_mass_solar_mass,stellar_surf_grav,...,spectral_type_KII,spectral_type_KIII,spectral_type_KIV,spectral_type_KV,spectral_type_MIII,spectral_type_MV,spectral_type_SD,spectral_type_T,spectral_type_WD,spectral_type_sdB
planet_name,,,,,,,,,,,,,,,,,,,,,
11 Com b,2.0,0.888737,1.226000,61.636581,5505.066162,2.561322,0.832987,13.760000,2.090000,2.380000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11 UMi b,1.0,1.413295,1.526667,57.057421,4684.814200,2.856345,0.740904,26.935000,2.780000,1.765000,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14 And b,1.0,0.510048,0.761667,30.026230,1224.550434,2.967550,0.840350,11.275000,1.780000,2.590000,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14 Her b,1.0,4.835948,2.814750,42.726171,2559.472162,0.501817,0.917704,0.999085,0.904000,4.418006,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
16 Cyg B b,3.0,2.188510,1.662833,20.176910,533.514528,0.750641,0.992480,1.129135,1.016599,4.342293,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ups And b,2.0,0.012638,0.058895,13.205018,219.960419,5.110508,1.063378,1.614742,1.276049,4.161529,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ups And c,2.0,0.659061,0.827712,21.840560,629.595000,1.358604,1.059787,1.614742,1.301399,4.148705,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ups And d,2.0,3.518990,2.528382,31.047562,1313.220000,0.777340,1.059787,1.614742,1.301399,4.148705,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0


In [518]:
# removing habitable zone column from the earth dataframe
earth_no_hab_zone = earth.drop(columns=['habitable_zone_main_seq'])
earth_no_hab_zone

,star_number_per_system,orbital_period_day,orbit_semi_major_axis_au,planet_rad_earth_rad,planet_mass_earth_mass,planet_equil_temp_k,stellar_effective_temp_k,stellar_rad_solar_rad,stellar_mass_solar_mass,stellar_surf_grav,...,spectral_type_KII,spectral_type_KIII,spectral_type_KIV,spectral_type_KV,spectral_type_MIII,spectral_type_MV,spectral_type_SD,spectral_type_T,spectral_type_WD,spectral_type_sdB
planet_name,,,,,,,,,,,,,,,,,,,,,
Earth,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0


## **Experiment #2 Ablation (No Habitable Zone) Manhattan Distance KNN Model #17**

In [519]:
# Fit Nearest Neighbors model with 10 closest neighbors using minkowski distance where p = 1 (manhattan distance)
nbrs = NearestNeighbors(n_neighbors=10, metric='minkowski', p=1).fit(experiment_2_ablation_no_hab_zone)

# Find the top 10 most similar rows
distances, indices = nbrs.kneighbors(earth_no_hab_zone)

# Retrieve the 10 closest planet names
closest_planets_man8 = experiment_2_ablation_no_hab_zone.index[indices[0]].tolist()
closest_distances_man8 = distances[0].tolist()

# Print the results
print("Top 10 most similar planets:")
for i in range(10):
    print(f"{i+1}. {closest_planets_man8[i]} (Distance: {closest_distances_man8[i]:.4f})")

Top 10 most similar planets:
1. Kepler-1185 b (Distance: 6.7585)
2. Kepler-452 b (Distance: 6.7993)
3. Kepler-132 e (Distance: 7.4888)
4. Kepler-1126 c (Distance: 7.5760)
5. Kepler-384 c (Distance: 7.7051)
6. Kepler-1253 b (Distance: 7.8426)
7. Kepler-1965 b (Distance: 7.9975)
8. Kepler-1440 b (Distance: 8.0092)
9. Kepler-1605 b (Distance: 8.0991)
10. Kepler-1505 b (Distance: 8.3436)


## **Experiment #2 Ablation (No Habitable Zone) Euclidean Distance KNN Model #18**

In [520]:
#Fit Nearest Neighbors model with 10 closest neighbors using minkowski distance where p = 2 (euclidean distance)
nbrs = NearestNeighbors(n_neighbors=10, metric='minkowski', p=2).fit(experiment_2_ablation_no_hab_zone)

# Find the top 10 most similar rows
distances, indices = nbrs.kneighbors(earth_no_hab_zone)

# Retrieve the 10 closest planet names
closest_planets_euc8 = experiment_2_ablation_no_hab_zone.index[indices[0]].tolist()
closest_distances_euc8 = distances[0].tolist()

# Print the results
print("Top 10 most similar planets:")
for i in range(10):
    print(f"{i+1}. {closest_planets_euc8[i]} (Distance: {closest_distances_euc8[i]:.4f})")

Top 10 most similar planets:
1. Kepler-1185 b (Distance: 3.6564)
2. Kepler-1253 b (Distance: 3.6823)
3. Kepler-132 e (Distance: 3.7144)
4. Kepler-384 c (Distance: 3.7627)
5. Kepler-130 d (Distance: 3.8319)
6. Kepler-1440 b (Distance: 3.8574)
7. Kepler-1498 b (Distance: 3.8688)
8. Kepler-1441 b (Distance: 3.9188)
9. Kepler-1965 b (Distance: 3.9808)
10. Kepler-1620 b (Distance: 3.9871)


### Preparing Dataset for Experiment #2 Ablation (No Temperature Features) KNN Models #19 and #20

In [521]:
# removing temperature features from the experiment_2_ablation dataframe
experiment_2_ablation_no_temp = experiment_2_ablation.drop(columns=['planet_equil_temp_k', 'stellar_effective_temp_k'])
experiment_2_ablation_no_temp

,star_number_per_system,orbital_period_day,orbit_semi_major_axis_au,planet_rad_earth_rad,planet_mass_earth_mass,stellar_rad_solar_rad,stellar_mass_solar_mass,stellar_surf_grav,stellar_luminosity_solar_lum,planet_orbital_velocity,...,spectral_type_KII,spectral_type_KIII,spectral_type_KIV,spectral_type_KV,spectral_type_MIII,spectral_type_MV,spectral_type_SD,spectral_type_T,spectral_type_WD,spectral_type_sdB
planet_name,,,,,,,,,,,,,,,,,,,,,
11 Com b,2.0,0.888737,1.226000,61.636581,5505.066162,13.760000,2.090000,2.380000,90.778824,1.305879,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11 UMi b,1.0,1.413295,1.526667,57.057421,4684.814200,26.935000,2.780000,1.765000,217.709668,1.349663,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14 And b,1.0,0.510048,0.761667,30.026230,1224.550434,11.275000,1.780000,2.590000,63.134826,1.528982,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14 Her b,1.0,4.835948,2.814750,42.726171,2559.472162,0.999085,0.904000,4.418006,0.705033,0.566812,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
16 Cyg B b,3.0,2.188510,1.662833,20.176910,533.514528,1.129135,1.016599,4.342293,1.231895,0.782034,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ups And b,2.0,0.012638,0.058895,13.205018,219.960419,1.614742,1.276049,4.161529,3.320113,4.655553,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ups And c,2.0,0.659061,0.827712,21.840560,629.595000,1.614742,1.301399,4.148705,3.275493,1.254124,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ups And d,2.0,3.518990,2.528382,31.047562,1313.220000,1.614742,1.301399,4.148705,3.275493,0.717561,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0


In [522]:
# removing temperature features from the earth dataframe
earth_no_temp = earth.drop(columns=['planet_equil_temp_k', 'stellar_effective_temp_k'])
earth_no_temp

,star_number_per_system,orbital_period_day,orbit_semi_major_axis_au,planet_rad_earth_rad,planet_mass_earth_mass,stellar_rad_solar_rad,stellar_mass_solar_mass,stellar_surf_grav,stellar_luminosity_solar_lum,planet_orbital_velocity,...,spectral_type_KII,spectral_type_KIII,spectral_type_KIV,spectral_type_KV,spectral_type_MIII,spectral_type_MV,spectral_type_SD,spectral_type_T,spectral_type_WD,spectral_type_sdB
planet_name,,,,,,,,,,,,,,,,,,,,,
Earth,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0


## **Experiment #2 Ablation (No Temperature Feature) Manhattan Distance KNN Model #19**

In [523]:
# Fit Nearest Neighbors model with 10 closest neighbors using minkowski distance where p = 1 (manhattan distance)
nbrs = NearestNeighbors(n_neighbors=10, metric='minkowski', p=1).fit(experiment_2_ablation_no_temp)

# Find the top 10 most similar rows
distances, indices = nbrs.kneighbors(earth_no_temp)

# Retrieve the 10 closest planet names
closest_planets_man9 = experiment_2_ablation_no_temp.index[indices[0]].tolist()
closest_distances_man9 = distances[0].tolist()

# Print the results
print("Top 10 most similar planets:")
for i in range(10):
    print(f"{i+1}. {closest_planets_man9[i]} (Distance: {closest_distances_man9[i]:.4f})")

Top 10 most similar planets:
1. Kepler-452 b (Distance: 6.7062)
2. Kepler-1185 b (Distance: 7.3187)
3. Kepler-1605 b (Distance: 7.3796)
4. Kepler-384 c (Distance: 7.7107)
5. Kepler-1440 b (Distance: 7.7497)
6. Kepler-1570 b (Distance: 7.7627)
7. Kepler-132 e (Distance: 7.8679)
8. Kepler-1253 b (Distance: 7.9355)
9. Kepler-1505 b (Distance: 7.9812)
10. Kepler-1965 b (Distance: 8.0580)


## **Experiment #2 Ablation (No Temperature Feature) Euclidean Distance KNN Model #20**

In [524]:
#Fit Nearest Neighbors model with 10 closest neighbors using minkowski distance where p = 2 (euclidean distance)
nbrs = NearestNeighbors(n_neighbors=10, metric='minkowski', p=2).fit(experiment_2_ablation_no_temp)

# Find the top 10 most similar rows
distances, indices = nbrs.kneighbors(earth_no_temp)

# Retrieve the 10 closest planet names
closest_planets_euc9 = experiment_2_ablation_no_temp.index[indices[0]].tolist()
closest_distances_euc9 = distances[0].tolist()

# Print the results
print("Top 10 most similar planets:")
for i in range(10):
    print(f"{i+1}. {closest_planets_euc9[i]} (Distance: {closest_distances_euc9[i]:.4f})")

Top 10 most similar planets:
1. Kepler-1570 b (Distance: 3.6580)
2. Kepler-1253 b (Distance: 3.7085)
3. Kepler-1185 b (Distance: 3.7658)
4. Kepler-384 c (Distance: 3.7722)
5. Kepler-1440 b (Distance: 3.7817)
6. Kepler-132 e (Distance: 3.8004)
7. Kepler-1605 b (Distance: 3.8834)
8. Kepler-130 d (Distance: 3.8875)
9. Kepler-1441 b (Distance: 3.8964)
10. Kepler-1498 b (Distance: 3.8966)


-------------

# **Experiment #3: Weight Sensitivity Analysis**

Planetary features +20%: increase planet radius, planet mass, planet equilibrium temperature, and planetary orbital velocity weights by 20%

In [525]:
# dataset for Planetary features +20% experiment #3
experiment_3_analysis_1 = experiment_3.copy()
experiment_3_analysis_1

,star_number_per_system,orbital_period_day,orbit_semi_major_axis_au,planet_rad_earth_rad,planet_mass_earth_mass,planet_equil_temp_k,stellar_effective_temp_k,stellar_rad_solar_rad,stellar_mass_solar_mass,stellar_surf_grav,...,spectral_type_KII,spectral_type_KIII,spectral_type_KIV,spectral_type_KV,spectral_type_MIII,spectral_type_MV,spectral_type_SD,spectral_type_T,spectral_type_WD,spectral_type_sdB
planet_name,,,,,,,,,,,,,,,,,,,,,
11 Com b,2.0,0.888737,1.226000,61.636581,5505.066162,2.561322,0.832987,13.760000,2.090000,2.380000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11 UMi b,1.0,1.413295,1.526667,57.057421,4684.814200,2.856345,0.740904,26.935000,2.780000,1.765000,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14 And b,1.0,0.510048,0.761667,30.026230,1224.550434,2.967550,0.840350,11.275000,1.780000,2.590000,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14 Her b,1.0,4.835948,2.814750,42.726171,2559.472162,0.501817,0.917704,0.999085,0.904000,4.418006,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
16 Cyg B b,3.0,2.188510,1.662833,20.176910,533.514528,0.750641,0.992480,1.129135,1.016599,4.342293,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ups And b,2.0,0.012638,0.058895,13.205018,219.960419,5.110508,1.063378,1.614742,1.276049,4.161529,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ups And c,2.0,0.659061,0.827712,21.840560,629.595000,1.358604,1.059787,1.614742,1.301399,4.148705,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ups And d,2.0,3.518990,2.528382,31.047562,1313.220000,0.777340,1.059787,1.614742,1.301399,4.148705,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0


In [526]:
# earth dataset for Planetary features +20% experiment #3
earth_3_analysis_1 = earth_3.copy()
earth_3_analysis_1

,star_number_per_system,orbital_period_day,orbit_semi_major_axis_au,planet_rad_earth_rad,planet_mass_earth_mass,planet_equil_temp_k,stellar_effective_temp_k,stellar_rad_solar_rad,stellar_mass_solar_mass,stellar_surf_grav,...,spectral_type_KII,spectral_type_KIII,spectral_type_KIV,spectral_type_KV,spectral_type_MIII,spectral_type_MV,spectral_type_SD,spectral_type_T,spectral_type_WD,spectral_type_sdB
planet_name,,,,,,,,,,,,,,,,,,,,,
Earth,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0


In [527]:
# weights applied (planet features: +20%) (all other features: no weights applied)
weights = {
    'star_number_per_system': 1.0,
    'orbital_period_day': 1.0,
    'orbit_semi_major_axis_au': 1.0,
    'planet_rad_earth_rad': 1.2,
    'planet_mass_earth_mass': 1.2,
    'planet_equil_temp_k': 1.2,
    'stellar_effective_temp_k': 1.0,
    'stellar_rad_solar_rad': 1.0,
    'stellar_mass_solar_mass': 1.0,
    'stellar_surf_grav': 1.0,
    'stellar_luminosity_solar_lum': 1.0,
    'planet_orbital_velocity': 1.2,
    'spectral_type_AIII': 1.0,
    'spectral_type_AIV': 1.0,
    'spectral_type_AV': 1.0,
    'spectral_type_BIV': 1.0,
    'spectral_type_BV': 1.0,
    'spectral_type_FIV': 1.0,
    'spectral_type_FV': 1.0,
    'spectral_type_GII': 1.0,
    'spectral_type_GIII': 1.0,
    'spectral_type_GIV': 1.0,
    'spectral_type_GV': 1.0,
    'spectral_type_KII': 1.0,
    'spectral_type_KIII': 1.0,
    'spectral_type_KIV': 1.0,
    'spectral_type_KV': 1.0,
    'spectral_type_MIII': 1.0,
    'spectral_type_MV': 1.0,
    'spectral_type_SD': 1.0,
    'spectral_type_T': 1.0,
    'spectral_type_WD': 1.0,
    'spectral_type_sdB': 1.0,
    'habitable_zone_main_seq': 1.0,
}

# Apply weights
for col in experiment_3_analysis_1.columns:
    weight = weights.get(col, 1.0)
    experiment_3_analysis_1[col] *= weight
    earth[col] *= weight

In [528]:
planetary_features = [
    'planet_rad_earth_rad',
    'planet_mass_earth_mass',
    'planet_equil_temp_k',
    'planet_orbital_velocity'
]

experiment_3_analysis_1 = experiment_3_analysis_1[planetary_features]

In [529]:
experiment_3_analysis_1

,planet_rad_earth_rad,planet_mass_earth_mass,planet_equil_temp_k,planet_orbital_velocity
planet_name,,,,
11 Com b,73.963897,6606.079394,3.073587,1.567055
11 UMi b,68.468905,5621.777040,3.427614,1.619595
14 And b,36.031476,1469.460520,3.561060,1.834779
14 Her b,51.271405,3071.366594,0.602181,0.680175
16 Cyg B b,24.212292,640.217434,0.900769,0.938441
...,...,...,...,...
ups And b,15.846022,263.952503,6.132610,5.586663
ups And c,26.208672,755.514000,1.630324,1.504949
ups And d,37.257075,1575.864000,0.932808,0.861073


In [530]:
earth_3_analysis_1 = earth_3_analysis_1[planetary_features]

In [531]:
earth_3_analysis_1

,planet_rad_earth_rad,planet_mass_earth_mass,planet_equil_temp_k,planet_orbital_velocity
planet_name,,,,
Earth,1.0,1.0,1.0,1.0


## **Experiment #3 Weight Sensitivity Analysis (Planetary features +20%) Manhattan Distance KNN Model #21**

In [532]:
# Fit Nearest Neighbors model with 10 closest neighbors using minkowski distance where p = 1 (manhattan distance)
nbrs = NearestNeighbors(n_neighbors=10, metric='minkowski', p=1).fit(experiment_3_analysis_1)

# Find the top 10 most similar rows
distances, indices = nbrs.kneighbors(earth_3_analysis_1)

# Retrieve the 10 closest planet names
closest_planets_man10 = experiment_3_analysis_1.index[indices[0]].tolist()
closest_distances_man10 = distances[0].tolist()

# Print the results
print("Top 10 most similar planets:")
for i in range(10):
    print(f"{i+1}. {closest_planets_man10[i]} (Distance: {closest_distances_man10[i]:.4f})")

Top 10 most similar planets:
1. Teegarden's Star d (Distance: 0.6882)
2. TRAPPIST-1 f (Distance: 1.1559)
3. Teegarden's Star c (Distance: 1.2848)
4. Kepler-186 f (Distance: 1.3077)
5. TRAPPIST-1 h (Distance: 1.3183)
6. Proxima Cen b (Distance: 1.5228)
7. TRAPPIST-1 e (Distance: 1.5261)
8. TOI-700 e (Distance: 1.5529)
9. GJ 1002 b (Distance: 1.5725)
10. TRAPPIST-1 g (Distance: 1.5989)


## **Experiment #3 Weight Sensitivity Analysis (Planetary features +20%) Euclidean Distance KNN Model #22**

In [533]:
# Fit Nearest Neighbors model with 10 closest neighbors using euclidean distance where p = 2 (manhattan distance)
nbrs = NearestNeighbors(n_neighbors=10, metric='euclidean', p=2).fit(experiment_3_analysis_1)

# Find the top 10 most similar rows
distances, indices = nbrs.kneighbors(earth_3_analysis_1)

# Retrieve the 10 closest planet names
closest_planets_euc10 = experiment_3_analysis_1.index[indices[0]].tolist()
closest_distances_euc10 = distances[0].tolist()

# Print the results
print("Top 10 most similar planets:")
for i in range(10):
    print(f"{i+1}. {closest_planets_euc10[i]} (Distance: {closest_distances_euc10[i]:.4f})")

Top 10 most similar planets:
1. Teegarden's Star d (Distance: 0.4246)
2. Kepler-186 f (Distance: 0.6840)
3. TRAPPIST-1 h (Distance: 0.7719)
4. Teegarden's Star c (Distance: 0.8228)
5. TRAPPIST-1 f (Distance: 0.8543)
6. TRAPPIST-1 g (Distance: 0.9088)
7. GJ 1002 c (Distance: 0.9242)
8. Proxima Cen b (Distance: 0.9904)
9. GJ 1002 b (Distance: 1.0237)
10. Wolf 1069 b (Distance: 1.0977)


In [534]:
all_distances, all_indices = nbrs.kneighbors(earth_3_analysis_1, n_neighbors=len(experiment_3_analysis_1))

# Map indices to names
all_planets = experiment_3_analysis_1.index[all_indices[0]]

# enter name of specifc planet to check its ranking
planet_to_check = 'Kepler-452 b'

# Find rank of Kepler-452 b
if planet_to_check in all_planets:
    rank = list(all_planets).index(planet_to_check) + 1
    distance = all_distances[0][rank-1]
    print(f"{planet_to_check} is ranked #{rank} overall with distance {distance:.4f}")
else:
    print(f"{planet_to_check} not found in dataset.")

Kepler-452 b is ranked #170 overall with distance 3.1129


In [535]:
experiment_3_analysis_1.loc[["Kepler-452 b"]]

,planet_rad_earth_rad,planet_mass_earth_mass,planet_equil_temp_k,planet_orbital_velocity
planet_name,,,,
Kepler-452 b,1.956,3.952929,1.105882,1.211996


In [536]:
experiment_3_analysis_1.loc[["Teegarden's Star d"]]

,planet_rad_earth_rad,planet_mass_earth_mass,planet_equil_temp_k,planet_orbital_velocity
planet_name,,,,
Teegarden's Star d,1.091299,0.984,0.748235,1.329088


Planetary features -20%: decrease those planetary feature weights by 20%

In [537]:
# dataset for Planetary features -20% experiment #3
experiment_3_analysis_2 = experiment_3.copy()
experiment_3_analysis_2

,star_number_per_system,orbital_period_day,orbit_semi_major_axis_au,planet_rad_earth_rad,planet_mass_earth_mass,planet_equil_temp_k,stellar_effective_temp_k,stellar_rad_solar_rad,stellar_mass_solar_mass,stellar_surf_grav,...,spectral_type_KII,spectral_type_KIII,spectral_type_KIV,spectral_type_KV,spectral_type_MIII,spectral_type_MV,spectral_type_SD,spectral_type_T,spectral_type_WD,spectral_type_sdB
planet_name,,,,,,,,,,,,,,,,,,,,,
11 Com b,2.0,0.888737,1.226000,61.636581,5505.066162,2.561322,0.832987,13.760000,2.090000,2.380000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11 UMi b,1.0,1.413295,1.526667,57.057421,4684.814200,2.856345,0.740904,26.935000,2.780000,1.765000,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14 And b,1.0,0.510048,0.761667,30.026230,1224.550434,2.967550,0.840350,11.275000,1.780000,2.590000,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14 Her b,1.0,4.835948,2.814750,42.726171,2559.472162,0.501817,0.917704,0.999085,0.904000,4.418006,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
16 Cyg B b,3.0,2.188510,1.662833,20.176910,533.514528,0.750641,0.992480,1.129135,1.016599,4.342293,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ups And b,2.0,0.012638,0.058895,13.205018,219.960419,5.110508,1.063378,1.614742,1.276049,4.161529,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ups And c,2.0,0.659061,0.827712,21.840560,629.595000,1.358604,1.059787,1.614742,1.301399,4.148705,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ups And d,2.0,3.518990,2.528382,31.047562,1313.220000,0.777340,1.059787,1.614742,1.301399,4.148705,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0


In [538]:
# earth dataset for Planetary features -20% experiment #3
earth_3_analysis_2 = earth_3.copy()
earth_3_analysis_2

,star_number_per_system,orbital_period_day,orbit_semi_major_axis_au,planet_rad_earth_rad,planet_mass_earth_mass,planet_equil_temp_k,stellar_effective_temp_k,stellar_rad_solar_rad,stellar_mass_solar_mass,stellar_surf_grav,...,spectral_type_KII,spectral_type_KIII,spectral_type_KIV,spectral_type_KV,spectral_type_MIII,spectral_type_MV,spectral_type_SD,spectral_type_T,spectral_type_WD,spectral_type_sdB
planet_name,,,,,,,,,,,,,,,,,,,,,
Earth,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0


In [539]:
# weights applied (planet features: -20%) (all other features: no weights applied)
weights = {
    'star_number_per_system': 1.0,
    'orbital_period_day': 1.0,
    'orbit_semi_major_axis_au': 1.0,
    'planet_rad_earth_rad': 0.8,
    'planet_mass_earth_mass': 0.8,
    'planet_equil_temp_k': 0.8,
    'stellar_effective_temp_k': 1.0,
    'stellar_rad_solar_rad': 1.0,
    'stellar_mass_solar_mass': 1.0,
    'stellar_surf_grav': 1.0,
    'stellar_luminosity_solar_lum': 1.0,
    'planet_orbital_velocity': 0.8,
    'spectral_type_AIII': 1.0,
    'spectral_type_AIV': 1.0,
    'spectral_type_AV': 1.0,
    'spectral_type_BIV': 1.0,
    'spectral_type_BV': 1.0,
    'spectral_type_FIV': 1.0,
    'spectral_type_FV': 1.0,
    'spectral_type_GII': 1.0,
    'spectral_type_GIII': 1.0,
    'spectral_type_GIV': 1.0,
    'spectral_type_GV': 1.0,
    'spectral_type_KII': 1.0,
    'spectral_type_KIII': 1.0,
    'spectral_type_KIV': 1.0,
    'spectral_type_KV': 1.0,
    'spectral_type_MIII': 1.0,
    'spectral_type_MV': 1.0,
    'spectral_type_SD': 1.0,
    'spectral_type_T': 1.0,
    'spectral_type_WD': 1.0,
    'spectral_type_sdB': 1.0,
    'habitable_zone_main_seq': 1.0,
}

# Apply weights
for col in experiment_3_analysis_2.columns:
    weight = weights.get(col, 1.0)
    experiment_3_analysis_2[col] *= weight
    earth[col] *= weight

In [540]:
experiment_3_analysis_2 = experiment_3_analysis_2[planetary_features]
earth_3_analysis_2 = earth_3_analysis_2[planetary_features]

model #23

In [541]:
# Fit Nearest Neighbors model with 10 closest neighbors using minkowski distance where p = 1 (manhattan distance)
nbrs = NearestNeighbors(n_neighbors=10, metric='minkowski', p=1).fit(experiment_3_analysis_2)

# Find the top 10 most similar rows
distances, indices = nbrs.kneighbors(earth_3_analysis_2)

# Retrieve the 10 closest planet names
closest_planets_man11 = experiment_3_analysis_2.index[indices[0]].tolist()
closest_distances_man11 = distances[0].tolist()

# Print the results
print("Top 10 most similar planets:")
for i in range(10):
    print(f"{i+1}. {closest_planets_man11[i]} (Distance: {closest_distances_man11[i]:.4f})")

Top 10 most similar planets:
1. Kepler-132 e (Distance: 0.4982)
2. TOI-700 d (Distance: 0.5807)
3. TRAPPIST-1 g (Distance: 0.5838)
4. Kepler-367 c (Distance: 0.5881)
5. Wolf 1069 b (Distance: 0.5912)
6. Kepler-1185 b (Distance: 0.6031)
7. GJ 1002 c (Distance: 0.6115)
8. K2-72 e (Distance: 0.6593)
9. Kepler-186 f (Distance: 0.6749)
10. Kepler-220 e (Distance: 0.6752)


model #24

In [542]:
# Fit Nearest Neighbors model with 10 closest neighbors using euclidean distance where p = 2 (manhattan distance)
nbrs = NearestNeighbors(n_neighbors=10, metric='minkowski', p=2).fit(experiment_3_analysis_2)

# Find the top 10 most similar rows
distances, indices = nbrs.kneighbors(earth_3_analysis_2)

# Retrieve the 10 closest planet names
closest_planets_euc11 = experiment_3_analysis_2.index[indices[0]].tolist()
closest_distances_euc11 = distances[0].tolist()

# Print the results
print("Top 10 most similar planets:")
for i in range(10):
    print(f"{i+1}. {closest_planets_euc11[i]} (Distance: {closest_distances_euc11[i]:.4f})")

Top 10 most similar planets:
1. Kepler-1185 b (Distance: 0.3245)
2. Kepler-132 e (Distance: 0.3283)
3. TOI-700 d (Distance: 0.3354)
4. Wolf 1069 b (Distance: 0.3551)
5. K2-72 e (Distance: 0.3828)
6. TRAPPIST-1 g (Distance: 0.4022)
7. Kepler-1459 b (Distance: 0.4033)
8. Kepler-367 c (Distance: 0.4175)
9. Kepler-442 b (Distance: 0.4194)
10. Teegarden's Star c (Distance: 0.4346)


Full Stellar features +20%: increase stellar mass, stellar radius, stellar effective temperature, stellar luminosity, stellar surface gravity weights, and spectral type by 20%

In [543]:
# datasets for full stellar features +20% experiment #3
experiment_3_analysis_3 = experiment_3.copy()
earth_3_analysis_3 = earth_3.copy()

In [544]:
# weights applied (full stellar features: +20%) (all other features: no weights applied)
weights = {
    'star_number_per_system': 1.0,
    'orbital_period_day': 1.0,
    'orbit_semi_major_axis_au': 1.0,
    'planet_rad_earth_rad': 1.0,
    'planet_mass_earth_mass': 1.0,
    'planet_equil_temp_k': 1.0,
    'stellar_effective_temp_k': 1.2,
    'stellar_rad_solar_rad': 1.2,
    'stellar_mass_solar_mass': 1.2,
    'stellar_surf_grav': 1.2,
    'stellar_luminosity_solar_lum': 1.2,
    'planet_orbital_velocity': 1.0,
    'spectral_type_AIII': 1.2,
    'spectral_type_AIV': 1.2,
    'spectral_type_AV': 1.2,
    'spectral_type_BIV': 1.2,
    'spectral_type_BV': 1.2,
    'spectral_type_FIV': 1.2,
    'spectral_type_FV': 1.2,
    'spectral_type_GII': 1.2,
    'spectral_type_GIII': 1.2,
    'spectral_type_GIV': 1.2,
    'spectral_type_GV': 1.2,
    'spectral_type_KII': 1.2,
    'spectral_type_KIII': 1.2,
    'spectral_type_KIV': 1.2,
    'spectral_type_KV': 1.2,
    'spectral_type_MIII': 1.2,
    'spectral_type_MV': 1.2,
    'spectral_type_SD': 1.2,
    'spectral_type_T': 1.2,
    'spectral_type_WD': 1.2,
    'spectral_type_sdB': 1.2,
    'habitable_zone_main_seq': 1.0,
}

# Apply weights
for col in experiment_3_analysis_3.columns:
    weight = weights.get(col, 1.0)
    experiment_3_analysis_3[col] *= weight
    earth[col] *= weight

In [545]:
# drop the non-stellar columns so only full stellar features remain
experiment_3_analysis_3 = experiment_3_analysis_3.drop(columns=['star_number_per_system', 'orbital_period_day',
                                                                'orbit_semi_major_axis_au', 'planet_rad_earth_rad',
                                                                'planet_mass_earth_mass', 'planet_equil_temp_k',
                                                                'planet_orbital_velocity', 'habitable_zone_main_seq'])
earth_3_analysis_3 = earth_3_analysis_3.drop(columns=['star_number_per_system', 'orbital_period_day',
                                                                'orbit_semi_major_axis_au', 'planet_rad_earth_rad',
                                                                'planet_mass_earth_mass', 'planet_equil_temp_k',
                                                                'planet_orbital_velocity', 'habitable_zone_main_seq'])

model #25

In [546]:
# Fit Nearest Neighbors model with 10 closest neighbors using minkowski distance where p = 1 (manhattan distance)
nbrs = NearestNeighbors(n_neighbors=10, metric='minkowski', p=1).fit(experiment_3_analysis_3)

# Find the top 10 most similar rows
distances, indices = nbrs.kneighbors(earth_3_analysis_3)

# Retrieve the 10 closest planet names
closest_planets_man12 = experiment_3_analysis_3.index[indices[0]].tolist()
closest_distances_man12 = distances[0].tolist()

# Print the results
print("Top 10 most similar planets:")
for i in range(10):
    print(f"{i+1}. {closest_planets_man12[i]} (Distance: {closest_distances_man12[i]:.4f})")

Top 10 most similar planets:
1. Kepler-638 b (Distance: 4.4775)
2. Kepler-1772 b (Distance: 4.5907)
3. Kepler-1570 b (Distance: 4.6031)
4. Kepler-463 b (Distance: 4.6898)
5. Kepler-536 b (Distance: 4.7207)
6. Kepler-1933 b (Distance: 4.7262)
7. Kepler-1638 b (Distance: 4.7345)
8. Kepler-1625 b (Distance: 4.7532)
9. Kepler-1339 b (Distance: 4.7663)
10. Kepler-1296 b (Distance: 4.7791)


model #26

In [547]:
# Fit Nearest Neighbors model with 10 closest neighbors using euclidean distance where p = 2 (manhattan distance)
nbrs = NearestNeighbors(n_neighbors=10, metric='minkowski', p=2).fit(experiment_3_analysis_3)

# Find the top 10 most similar rows
distances, indices = nbrs.kneighbors(earth_3_analysis_3)

# Retrieve the 10 closest planet names
closest_planets_euc12 = experiment_3_analysis_3.index[indices[0]].tolist()
closest_distances_euc12 = distances[0].tolist()

# Print the results
print("Top 10 most similar planets:")
for i in range(10):
    print(f"{i+1}. {closest_planets_euc12[i]} (Distance: {closest_distances_euc12[i]:.4f})")

Top 10 most similar planets:
1. Kepler-1570 b (Distance: 3.7617)
2. Kepler-638 b (Distance: 3.7769)
3. Kepler-784 b (Distance: 3.7946)
4. Kepler-1772 b (Distance: 3.8276)
5. Kepler-525 b (Distance: 3.8403)
6. Kepler-806 b (Distance: 3.8685)
7. Kepler-796 b (Distance: 3.8774)
8. HD 95544 b (Distance: 3.9326)
9. TOI-261.01 (Distance: 3.9401)
10. Kepler-1929 b (Distance: 3.9482)


Full Stellar features -20%: decrease those full stellar feature weights by 20%

In [548]:
# datasets for full stellar features +20% experiment #3
experiment_3_analysis_4 = experiment_3.copy()
earth_3_analysis_4 = earth_3.copy()

In [549]:
# weights applied (full stellar features: +20%) (all other features: no weights applied)
weights = {
    'star_number_per_system': 1.0,
    'orbital_period_day': 1.0,
    'orbit_semi_major_axis_au': 1.0,
    'planet_rad_earth_rad': 1.0,
    'planet_mass_earth_mass': 1.0,
    'planet_equil_temp_k': 1.0,
    'stellar_effective_temp_k': 0.8,
    'stellar_rad_solar_rad': 0.8,
    'stellar_mass_solar_mass': 0.8,
    'stellar_surf_grav': 0.8,
    'stellar_luminosity_solar_lum': 0.8,
    'planet_orbital_velocity': 1.0,
    'spectral_type_AIII': 0.8,
    'spectral_type_AIV': 0.8,
    'spectral_type_AV': 0.8,
    'spectral_type_BIV': 0.8,
    'spectral_type_BV': 0.8,
    'spectral_type_FIV': 0.8,
    'spectral_type_FV': 0.8,
    'spectral_type_GII': 0.8,
    'spectral_type_GIII': 0.8,
    'spectral_type_GIV': 0.8,
    'spectral_type_GV': 0.8,
    'spectral_type_KII': 0.8,
    'spectral_type_KIII': 0.8,
    'spectral_type_KIV': 0.8,
    'spectral_type_KV': 0.8,
    'spectral_type_MIII': 0.8,
    'spectral_type_MV': 0.8,
    'spectral_type_SD': 0.8,
    'spectral_type_T': 0.8,
    'spectral_type_WD': 0.8,
    'spectral_type_sdB': 0.8,
    'habitable_zone_main_seq': 1.0,
}

# Apply weights
for col in experiment_3_analysis_4.columns:
    weight = weights.get(col, 1.0)
    experiment_3_analysis_4[col] *= weight
    earth[col] *= weight

In [550]:
# drop the non-stellar columns so only full stellar features remain
experiment_3_analysis_4 = experiment_3_analysis_4.drop(columns=['star_number_per_system', 'orbital_period_day',
                                                                'orbit_semi_major_axis_au', 'planet_rad_earth_rad',
                                                                'planet_mass_earth_mass', 'planet_equil_temp_k',
                                                                'planet_orbital_velocity', 'habitable_zone_main_seq'])
earth_3_analysis_4 = earth_3_analysis_4.drop(columns=['star_number_per_system', 'orbital_period_day',
                                                                'orbit_semi_major_axis_au', 'planet_rad_earth_rad',
                                                                'planet_mass_earth_mass', 'planet_equil_temp_k',
                                                                'planet_orbital_velocity', 'habitable_zone_main_seq'])

model #27

In [551]:
# Fit Nearest Neighbors model with 10 closest neighbors using minkowski distance where p = 1 (manhattan distance)
nbrs = NearestNeighbors(n_neighbors=10, metric='minkowski', p=1).fit(experiment_3_analysis_4)

# Find the top 10 most similar rows
distances, indices = nbrs.kneighbors(earth_3_analysis_4)

# Retrieve the 10 closest planet names
closest_planets_man13 = experiment_3_analysis_4.index[indices[0]].tolist()
closest_distances_man13 = distances[0].tolist()

# Print the results
print("Top 10 most similar planets:")
for i in range(10):
    print(f"{i+1}. {closest_planets_man13[i]} (Distance: {closest_distances_man13[i]:.4f})")

Top 10 most similar planets:
1. Kepler-806 b (Distance: 2.9153)
2. HAT-P-21 b (Distance: 2.9512)
3. Kepler-784 b (Distance: 2.9927)
4. Kepler-1888 b (Distance: 3.0227)
5. K2-24 b (Distance: 3.0251)
6. K2-24 c (Distance: 3.0251)
7. Kepler-654 b (Distance: 3.0283)
8. HD 95544 b (Distance: 3.0311)
9. Kepler-525 b (Distance: 3.0338)
10. Kepler-1777 b (Distance: 3.0478)


model #28

In [552]:
# Fit Nearest Neighbors model with 10 closest neighbors using euclidean distance where p = 2 (manhattan distance)
nbrs = NearestNeighbors(n_neighbors=10, metric='minkowski', p=2).fit(experiment_3_analysis_4)

# Find the top 10 most similar rows
distances, indices = nbrs.kneighbors(earth_3_analysis_4)

# Retrieve the 10 closest planet names
closest_planets_euc13 = experiment_3_analysis_4.index[indices[0]].tolist()
closest_distances_euc13 = distances[0].tolist()

# Print the results
print("Top 10 most similar planets:")
for i in range(10):
    print(f"{i+1}. {closest_planets_euc13[i]} (Distance: {closest_distances_euc13[i]:.4f})")

Top 10 most similar planets:
1. Kepler-784 b (Distance: 2.1313)
2. Kepler-1929 b (Distance: 2.1665)
3. Kepler-806 b (Distance: 2.2294)
4. Kepler-525 b (Distance: 2.2320)
5. NGTS-17 b (Distance: 2.2492)
6. Kepler-473 b (Distance: 2.2561)
7. HIP 67522 b (Distance: 2.2609)
8. Kepler-1570 b (Distance: 2.2610)
9. Kepler-1772 b (Distance: 2.2728)
10. TOI-261.01 (Distance: 2.2744)


Partial Stellar features +20%: increase stellar mass, stellar radius, stellar effective temperature, stellar luminosity, and stellar surface gravity weights by 20%

In [553]:
# datasets for partial stellar features +20% experiment #3
experiment_3_analysis_5 = experiment_3.copy()
earth_3_analysis_5 = earth_3.copy()

In [554]:
# weights applied (partial stellar features: +20%) (all other features: no weights applied)
weights = {
    'star_number_per_system': 1.0,
    'orbital_period_day': 1.0,
    'orbit_semi_major_axis_au': 1.0,
    'planet_rad_earth_rad': 1.0,
    'planet_mass_earth_mass': 1.0,
    'planet_equil_temp_k': 1.0,
    'stellar_effective_temp_k': 1.2,
    'stellar_rad_solar_rad': 1.2,
    'stellar_mass_solar_mass': 1.2,
    'stellar_surf_grav': 1.2,
    'stellar_luminosity_solar_lum': 1.2,
    'planet_orbital_velocity': 1.0,
    'spectral_type_AIII': 1.0,
    'spectral_type_AIV': 1.0,
    'spectral_type_AV': 1.0,
    'spectral_type_BIV': 1.0,
    'spectral_type_BV': 1.0,
    'spectral_type_FIV': 1.0,
    'spectral_type_FV': 1.0,
    'spectral_type_GII': 1.0,
    'spectral_type_GIII': 1.0,
    'spectral_type_GIV': 1.0,
    'spectral_type_GV': 1.0,
    'spectral_type_KII': 1.0,
    'spectral_type_KIII': 1.0,
    'spectral_type_KIV': 1.0,
    'spectral_type_KV': 1.0,
    'spectral_type_MIII': 1.0,
    'spectral_type_MV': 1.0,
    'spectral_type_SD': 1.0,
    'spectral_type_T': 1.0,
    'spectral_type_WD': 1.0,
    'spectral_type_sdB': 1.0,
    'habitable_zone_main_seq': 1.0,
}

# Apply weights
for col in experiment_3_analysis_5.columns:
    weight = weights.get(col, 1.0)
    experiment_3_analysis_5[col] *= weight
    earth[col] *= weight

In [555]:
stellar_features = [
    'stellar_effective_temp_k',
    'stellar_rad_solar_rad',
    'stellar_mass_solar_mass',
    'stellar_surf_grav',
    'stellar_luminosity_solar_lum'
]

experiment_3_analysis_5 = experiment_3_analysis_5[stellar_features]
earth_3_analysis_5 = earth_3_analysis_5[stellar_features]

model #29

In [556]:
# Fit Nearest Neighbors model with 10 closest neighbors using minkowski distance where p = 1 (manhattan distance)
nbrs = NearestNeighbors(n_neighbors=10, metric='minkowski', p=1).fit(experiment_3_analysis_5)

# Find the top 10 most similar rows
distances, indices = nbrs.kneighbors(earth_3_analysis_5)

# Retrieve the 10 closest planet names
closest_planets_man14 = experiment_3_analysis_5.index[indices[0]].tolist()
closest_distances_man14 = distances[0].tolist()

# Print the results
print("Top 10 most similar planets:")
for i in range(10):
    print(f"{i+1}. {closest_planets_man14[i]} (Distance: {closest_distances_man14[i]:.4f})")

Top 10 most similar planets:
1. Kepler-638 b (Distance: 4.2775)
2. Kepler-1772 b (Distance: 4.3907)
3. Kepler-1570 b (Distance: 4.4031)
4. Kepler-463 b (Distance: 4.4898)
5. Kepler-536 b (Distance: 4.5207)
6. Kepler-1933 b (Distance: 4.5262)
7. Kepler-1638 b (Distance: 4.5345)
8. Kepler-1625 b (Distance: 4.5532)
9. Kepler-1339 b (Distance: 4.5663)
10. Kepler-1296 b (Distance: 4.5791)


model #30

In [557]:
# Fit Nearest Neighbors model with 10 closest neighbors using euclidean distance where p = 2 (manhattan distance)
nbrs = NearestNeighbors(n_neighbors=10, metric='minkowski', p=2).fit(experiment_3_analysis_5)

# Find the top 10 most similar rows
distances, indices = nbrs.kneighbors(earth_3_analysis_5)

# Retrieve the 10 closest planet names
closest_planets_euc14 = experiment_3_analysis_5.index[indices[0]].tolist()
closest_distances_euc14 = distances[0].tolist()

# Print the results
print("Top 10 most similar planets:")
for i in range(10):
    print(f"{i+1}. {closest_planets_euc14[i]} (Distance: {closest_distances_euc14[i]:.4f})")

Top 10 most similar planets:
1. HD 10442 b (Distance: 3.7132)
2. GQ Lup b (Distance: 3.7295)
3. Kepler-1570 b (Distance: 3.7564)
4. Kepler-638 b (Distance: 3.7716)
5. CoRoT-28 b (Distance: 3.7844)
6. Kepler-784 b (Distance: 3.7893)
7. Kepler-1772 b (Distance: 3.8224)
8. Kepler-525 b (Distance: 3.8351)
9. Kepler-1423 b (Distance: 3.8480)
10. IRAS 04125+2902 b (Distance: 3.8489)


Partial Stellar features -20%: decrease those partial stellar feature weights by 20%

In [558]:
# datasets for partial stellar features -20% experiment #3
experiment_3_analysis_6 = experiment_3.copy()
earth_3_analysis_6 = earth_3.copy()

In [559]:
# weights applied (partial stellar features: -20%) (all other features: no weights applied)
weights = {
    'star_number_per_system': 1.0,
    'orbital_period_day': 1.0,
    'orbit_semi_major_axis_au': 1.0,
    'planet_rad_earth_rad': 1.0,
    'planet_mass_earth_mass': 1.0,
    'planet_equil_temp_k': 1.0,
    'stellar_effective_temp_k': 0.8,
    'stellar_rad_solar_rad': 0.8,
    'stellar_mass_solar_mass': 0.8,
    'stellar_surf_grav': 0.8,
    'stellar_luminosity_solar_lum': 0.8,
    'planet_orbital_velocity': 1.0,
    'spectral_type_AIII': 1.0,
    'spectral_type_AIV': 1.0,
    'spectral_type_AV': 1.0,
    'spectral_type_BIV': 1.0,
    'spectral_type_BV': 1.0,
    'spectral_type_FIV': 1.0,
    'spectral_type_FV': 1.0,
    'spectral_type_GII': 1.0,
    'spectral_type_GIII': 1.0,
    'spectral_type_GIV': 1.0,
    'spectral_type_GV': 1.0,
    'spectral_type_KII': 1.0,
    'spectral_type_KIII': 1.0,
    'spectral_type_KIV': 1.0,
    'spectral_type_KV': 1.0,
    'spectral_type_MIII': 1.0,
    'spectral_type_MV': 1.0,
    'spectral_type_SD': 1.0,
    'spectral_type_T': 1.0,
    'spectral_type_WD': 1.0,
    'spectral_type_sdB': 1.0,
    'habitable_zone_main_seq': 1.0,
}

# Apply weights
for col in experiment_3_analysis_6.columns:
    weight = weights.get(col, 1.0)
    experiment_3_analysis_6[col] *= weight
    earth[col] *= weight

In [560]:
experiment_3_analysis_6 = experiment_3_analysis_6[stellar_features]
earth_3_analysis_6 = earth_3_analysis_6[stellar_features]

model #31

In [561]:
# Fit Nearest Neighbors model with 10 closest neighbors using minkowski distance where p = 1 (manhattan distance)
nbrs = NearestNeighbors(n_neighbors=10, metric='minkowski', p=1).fit(experiment_3_analysis_6)

# Find the top 10 most similar rows
distances, indices = nbrs.kneighbors(earth_3_analysis_6)

# Retrieve the 10 closest planet names
closest_planets_man15 = experiment_3_analysis_6.index[indices[0]].tolist()
closest_distances_man15 = distances[0].tolist()

# Print the results
print("Top 10 most similar planets:")
for i in range(10):
    print(f"{i+1}. {closest_planets_man15[i]} (Distance: {closest_distances_man15[i]:.4f})")

Top 10 most similar planets:
1. Kepler-806 b (Distance: 2.7153)
2. HAT-P-21 b (Distance: 2.7512)
3. Kepler-784 b (Distance: 2.7927)
4. Kepler-1888 b (Distance: 2.8227)
5. Kepler-74 b (Distance: 2.8232)
6. K2-24 b (Distance: 2.8251)
7. K2-24 c (Distance: 2.8251)
8. Kepler-654 b (Distance: 2.8283)
9. HD 95544 b (Distance: 2.8311)
10. Kepler-525 b (Distance: 2.8338)


model #32

In [562]:
# Fit Nearest Neighbors model with 10 closest neighbors using euclidean distance where p = 2 (manhattan distance)
nbrs = NearestNeighbors(n_neighbors=10, metric='minkowski', p=2).fit(experiment_3_analysis_6)

# Find the top 10 most similar rows
distances, indices = nbrs.kneighbors(earth_3_analysis_6)

# Retrieve the 10 closest planet names
closest_planets_euc15 = experiment_3_analysis_6.index[indices[0]].tolist()
closest_distances_euc15 = distances[0].tolist()

# Print the results
print("Top 10 most similar planets:")
for i in range(10):
    print(f"{i+1}. {closest_planets_euc15[i]} (Distance: {closest_distances_euc15[i]:.4f})")

Top 10 most similar planets:
1. HD 10442 b (Distance: 1.9773)
2. CoRoT-28 b (Distance: 2.0476)
3. Kepler-784 b (Distance: 2.1219)
4. GQ Lup b (Distance: 2.1258)
5. Kepler-1929 b (Distance: 2.1573)
6. V830 Tau b (Distance: 2.2027)
7. Kepler-806 b (Distance: 2.2204)
8. Kepler-525 b (Distance: 2.2230)
9. K2-308 b (Distance: 2.2249)
10. NGTS-17 b (Distance: 2.2403)


Spectral-type features +20%: increase the one-hot encoded spectral-type feature weights by 20%

In [563]:
# datasets for partial stellar features +20% experiment #3
experiment_3_analysis_7 = experiment_3.copy()
earth_3_analysis_7 = earth_3.copy()

In [564]:
# weights applied (one hot encoded spectral features: +20%) (all other features: no weights applied)
weights = {
    'star_number_per_system': 1.0,
    'orbital_period_day': 1.0,
    'orbit_semi_major_axis_au': 1.0,
    'planet_rad_earth_rad': 1.0,
    'planet_mass_earth_mass': 1.0,
    'planet_equil_temp_k': 1.0,
    'stellar_effective_temp_k': 1.0,
    'stellar_rad_solar_rad': 1.0,
    'stellar_mass_solar_mass': 1.0,
    'stellar_surf_grav': 1.0,
    'stellar_luminosity_solar_lum': 1.0,
    'planet_orbital_velocity': 1.0,
    'spectral_type_AIII': 1.2,
    'spectral_type_AIV': 1.2,
    'spectral_type_AV': 1.2,
    'spectral_type_BIV': 1.2,
    'spectral_type_BV': 1.2,
    'spectral_type_FIV': 1.2,
    'spectral_type_FV': 1.2,
    'spectral_type_GII': 1.2,
    'spectral_type_GIII': 1.2,
    'spectral_type_GIV': 1.2,
    'spectral_type_GV': 1.2,
    'spectral_type_KII': 1.2,
    'spectral_type_KIII': 1.2,
    'spectral_type_KIV': 1.2,
    'spectral_type_KV': 1.2,
    'spectral_type_MIII': 1.2,
    'spectral_type_MV': 1.2,
    'spectral_type_SD': 1.2,
    'spectral_type_T': 1.2,
    'spectral_type_WD': 1.2,
    'spectral_type_sdB': 1.2,
    'habitable_zone_main_seq': 1.0,
}

# Apply weights
for col in experiment_3_analysis_7.columns:
    weight = weights.get(col, 1.0)
    experiment_3_analysis_7[col] *= weight
    earth[col] *= weight

In [565]:
# drop the non-spectal type so only one hot encoded spectral type columsn remain
experiment_3_analysis_7 = experiment_3_analysis_7.drop(columns=['star_number_per_system', 'orbital_period_day',
                                                                'orbit_semi_major_axis_au', 'planet_rad_earth_rad',
                                                                'planet_mass_earth_mass', 'planet_equil_temp_k',
                                                                'stellar_effective_temp_k', 'stellar_rad_solar_rad',
                                                                'stellar_mass_solar_mass', 'stellar_surf_grav',
                                                                'stellar_luminosity_solar_lum', 'planet_orbital_velocity',
                                                                'habitable_zone_main_seq'])
earth_3_analysis_7 = earth_3_analysis_7.drop(columns=['star_number_per_system', 'orbital_period_day',
                                                                'orbit_semi_major_axis_au', 'planet_rad_earth_rad',
                                                                'planet_mass_earth_mass', 'planet_equil_temp_k',
                                                                'stellar_effective_temp_k', 'stellar_rad_solar_rad',
                                                                'stellar_mass_solar_mass', 'stellar_surf_grav',
                                                                'stellar_luminosity_solar_lum', 'planet_orbital_velocity',
                                                                'habitable_zone_main_seq'])

model #33

In [566]:
# Fit Nearest Neighbors model with 10 closest neighbors using minkowski distance where p = 1 (manhattan distance)
nbrs = NearestNeighbors(n_neighbors=10, metric='minkowski', p=1).fit(experiment_3_analysis_7)

# Find the top 10 most similar rows
distances, indices = nbrs.kneighbors(earth_3_analysis_7)

# Retrieve the 10 closest planet names
closest_planets_man16 = experiment_3_analysis_7.index[indices[0]].tolist()
closest_distances_man16 = distances[0].tolist()

# Print the results
print("Top 10 most similar planets:")
for i in range(10):
    print(f"{i+1}. {closest_planets_man16[i]} (Distance: {closest_distances_man16[i]:.4f})")

Top 10 most similar planets:
1. 47 UMa d (Distance: 0.2000)
2. 16 Cyg B b (Distance: 0.2000)
3. 55 Cnc c (Distance: 0.2000)
4. 47 UMa c (Distance: 0.2000)
5. 55 Cnc e (Distance: 0.2000)
6. 51 Peg b (Distance: 0.2000)
7. 55 Cnc d (Distance: 0.2000)
8. 55 Cnc f (Distance: 0.2000)
9. 55 Cnc b (Distance: 0.2000)
10. 47 UMa b (Distance: 0.2000)


model #34

In [567]:
# Fit Nearest Neighbors model with 10 closest neighbors using euclidean distance where p = 2 (manhattan distance)
nbrs = NearestNeighbors(n_neighbors=10, metric='minkowski', p=2).fit(experiment_3_analysis_7)

# Find the top 10 most similar rows
distances, indices = nbrs.kneighbors(earth_3_analysis_7)

# Retrieve the 10 closest planet names
closest_planets_euc16 = experiment_3_analysis_7.index[indices[0]].tolist()
closest_distances_euc16 = distances[0].tolist()

# Print the results
print("Top 10 most similar planets:")
for i in range(10):
    print(f"{i+1}. {closest_planets_euc16[i]} (Distance: {closest_distances_euc16[i]:.4f})")

Top 10 most similar planets:
1. 47 UMa d (Distance: 0.2000)
2. 16 Cyg B b (Distance: 0.2000)
3. 55 Cnc c (Distance: 0.2000)
4. 47 UMa c (Distance: 0.2000)
5. 55 Cnc e (Distance: 0.2000)
6. 51 Peg b (Distance: 0.2000)
7. 55 Cnc d (Distance: 0.2000)
8. 55 Cnc f (Distance: 0.2000)
9. 55 Cnc b (Distance: 0.2000)
10. 47 UMa b (Distance: 0.2000)


Spectral-type features -20%: decrease the one-hot encoded spectral-type feature weights by 20%

Orbital/HZ features +20%: increase orbital period, orbital semi-major axis, and habitable-zone flag weights by 20%

Orbital/HZ features -20%: decrease those orbital/HZ feature weights by 20%